Initial repository setup
api3dao/airseeker-v1 pull request #1
Opened 2022-03-23 14:14 UTC by amarthadan

[BEC-245](https://api3dao.atlassian.net/browse/BEC-245)

2022-03-25 10:19 UTC, Siegrift requested changes
Some minor changes, but otherwise LGTM.

2022-03-25 10:19 UTC, Siegrift commented on .eslintignore
> +**/node_modules/**
It's pretty disapointing that these ignore files do not have an option to extend gitignore (which seems a pretty reasonable default).

For that reason I've started to like putting a comment to keep them in sync. See: https://github.com/api3dao/manager-multisig/blob/main/.gitignore#L1

Also, you should probably put all of the gitignore stuff here.

2022-03-25 10:19 UTC, Siegrift commented on .github/dependabot.yml
> +      - amarthadan
Feel free to add me as well.

2022-03-25 10:19 UTC, Siegrift commented on .eslintignore
> +.prettierignore
Nit: \n

2022-03-25 10:19 UTC, Siegrift commented on .prettierrc
> +  "overrides": [
I think you also want to add solidity support https://github.com/api3dao/airnode/pull/324/commits/e7c1bf033ac3e548b2bb8293a6abce5e8134a103

2022-03-28 11:57 UTC, amarthadan commented on .prettierrc
> +  "overrides": [
I'll do that once it's needed.

2022-03-28 14:01 UTC, Siegrift approved these changes
LGTM

2022-03-29 06:13 UTC, merged