Implement API request fetching
api3dao/airseeker-v1 pull request #13
Opened 2022-04-07 15:48 UTC by Siegrift

https://api3dao.atlassian.net/browse/BEC-247

2022-04-09 14:57 UTC, vponline commented on jest.config.js
> +  resetMocks: true,
> I found out that the jest configuration does not reset mocks which caused me a lot of pain... I've enabled the "good defaults" now

Just wanted to note that this setting is not enabled in Airnode or Airkeeper and caused some confusion for me as well :sweat_smile: 

If this is enabled it means mocks/spys cannot be defined in the `describe`-block (they will return undefined) and instead need to be in a `beforeEach` or directly in the test `it`-block, more info [here](https://github.com/facebook/jest/issues/9131#issuecomment-668790615)

No need to change, just more of an FYI if you are puzzled by mocks returning undefined :smile:

2022-04-11 08:09 UTC, amarthadan requested changes

2022-04-11 08:09 UTC, amarthadan commented on package.json
> +    "test:debug": "jest \"fetch-beacon-data.test.ts\""
Same as in the previous PR.

2022-04-11 08:09 UTC, amarthadan commented on src/fetch-beacon-data.test.ts
> +              heartbeatInterval: 86400,
```suggestion
              heartbeatInterval: 86_400,
```

2022-04-11 08:09 UTC, amarthadan commented on src/fetch-beacon-data.test.ts
> +              heartbeatInterval: 86400,
```suggestion
              heartbeatInterval: 86_400,
```

2022-04-11 08:09 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +    updateState((state) => ({ ...state, beaconValues: { ...state.beaconValues, [beaconId]: goRes.data } }));
This `goRes` is of type `GoResult<GoResult<any, Error>, Error>`. We shouldn't wrap those go results inside one another because the `goRes.data` at the end is actually of type `GoResult` (an object) and not the resulting data which is what we want.

2022-04-11 08:09 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +import { performance } from 'perf_hooks';
What is the advantage of using `performance` in comparison with normal `Date`?

2022-04-11 08:09 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +    const waitTime = Math.max(0, fetchInterval * 1_000 - duration);
I understand what's happening here but can you maybe add a comment describing why you calculate the wait time the way you do?

2022-04-11 08:09 UTC, amarthadan commented on src/main.ts
> +import { join } from 'path';
I don't like this much because the name like `join` is so generic that having it prefixed like `path.join` actually helps when you're reading the code. We don't need to care about the side in this case (we're not building it for web) so I would rather stick with the prefixed version. Actually even for the `lodash`.

2022-04-11 08:51 UTC, Siegrift commented on src/fetch-beacon-data.ts
> +import { performance } from 'perf_hooks';
Not much, it's more precise but slower. Thinking about this once more I think we are more interested in performance here rather then accuracy.

I'll revert.

2022-04-11 13:51 UTC, Siegrift commented on src/fetch-beacon-data.ts
> +    updateState((state) => ({ ...state, beaconValues: { ...state.beaconValues, [beaconId]: goRes.data } }));
Yeah, that will be changed when the makeSignedDataGatewayRequest fn will be implemented. I initially assumed it will return go response, but I've changed that to `SignedData | null`.

I'm returning `any` type in this PR.

2022-04-11 14:11 UTC, Siegrift commented on src/main.ts
> +import { join } from 'path';
Reverted.

2022-04-12 06:36 UTC, amarthadan approved these changes

2022-04-12 07:16 UTC, merged