BEC258: Terraform ECS
api3dao/airseeker-v1 pull request #14
Opened 2022-04-07 17:49 UTC by acenolaza

I'm creating this as a WIP because I wanted to get feedback as soon as possible and also because the Airseeker docket image [is not yet in docker hub](https://api3dao.atlassian.net/browse/BEC-300).

Some notes:
1. Created an ecs cluster, task definition and service to tie them together.
2. Since I'm using FARGATE I had to add a vpc resource but since we are not exposing a frontend I didn't think it was necessary to deal with internet gateways, load balancers and security groups. The simplest way I found to add a vpc is to just define a default vpc resource with default subnets.
3. Since I wanted to add logs to the task (awslogs set in the Task Definition) I had to also attach the `AmazonECSTaskExecutionRolePolicy`.
4. I've hardcoded the airnode-client docker image url just for testing until airseeker image is ready. Once that happens I guess I'll replace it with a variable.
5. I wasn't sure if we needed to deploy to different stages so I decided to keep it simple and have all terraform files in the same directory. Also I have not created any modules until I see the need for them.

2022-04-08 10:20 UTC, amarthadan requested changes

2022-04-08 10:20 UTC, amarthadan commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
This should not be in the repo.

2022-04-08 10:20 UTC, amarthadan commented on terraform/network.tf
> +}
I would definitely not use the default AWS resources. As from the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_vpc), they are not created by Terraform (if it already exists) but it's just adopted. It's kind of a shared resource and its configuration may unexpectedly change (from within another project for example). I know that the AWS networking is a bit tricky but it's not that complicated and there's a lot of tutorials on how to set the basic one (which is what we need).

2022-04-08 10:20 UTC, amarthadan commented on terraform/providers.tf
> +terraform {
I think we should use an AWS backend (S3 bucket) for storing the state file. Even without the locking to avoid the need for DynamoDB.

2022-04-08 10:20 UTC, amarthadan commented on terraform/variables.tf
> +  default     = "production"
The default should not be a production, you don't want someone to deploy the production version just be accidentally running the recipes :sweat_smile:

2022-04-08 10:20 UTC, amarthadan commented on terraform/variables.tf
> +  app_name    = "Airseeker"
Some resources require their name to be in lower case and since you're using this as part of the name it should be lower case too.

2022-04-08 10:20 UTC, amarthadan commented on terraform/main.tf
> +      "memory": 512,
Things like these, log retention period, etc should be configurable via variables.

2022-04-08 10:20 UTC, amarthadan commented on terraform/variables.tf
> +locals {
You can create something like `resource_prefix = "${app_name}-${environment}"` and use it as a prefix for all the resources (even tags). That way, we would be able to deploy to two different environments with the same recipes (hopefully :smile:).

2022-04-08 10:20 UTC, amarthadan commented on terraform/network.tf
> +}
If I understand it correctly, we need the setup described on [this documentation page](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html#fargate-tasks-services).
`For a Fargate task in a private subnet to pull container images, you need a NAT gateway in the subnet to route requests to the internet.`
we don't need the task to be public (there's no need to access it from outside) and therefore we also don't need any load balancers.

2022-04-08 10:20 UTC, amarthadan commented on terraform/roles.tf
> +      identifiers = ["ecs-tasks.amazonaws.com", "ec2.amazonaws.com", "ecs.amazonaws.com"]
Isn't `ecs-tasks.amazonaws.com` enought?

2022-04-08 10:20 UTC, amarthadan commented on terraform/roles.tf
> +  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
I would prefer using a custom policy that allows only exactly what we need and that is writing logs. Take a look at [this Airnode one](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/terraform/airnode/aws/modules/function/data.tf#L15), that should be enough.

2022-04-08 11:37 UTC, aquarat commented on terraform/variables.tf
> +  default     = "production"
Like I did recently with something :shushing_face:

2022-04-11 12:03 UTC, acenolaza commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
I'll remove this file from source control. I thought it was OK to add it because chainapi do have them in the repo: https://github.com/chainapi/infrastructure/blob/26f5e901baea79a4a52b8628e96230ea4950a17d/prod/.terraform.lock.hcl

2022-04-11 14:21 UTC, acenolaza commented on terraform/variables.tf
> +  default     = "production"
I like to live on the edge 😅

2022-04-11 14:29 UTC, acenolaza commented on terraform/main.tf
> +      "memory": 512,
[ChainAPI](https://github.com/chainapi/infrastructure/blob/4dbe6de735b19805f9fc1b54325cc09f9ce31ed0/modules/ecs/main.tf) is using 180 but [airnode-deployer](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/terraform/airnode/aws/modules/function/main.tf#L30) uses 90 days. Which value do you think is better?

2022-04-12 06:39 UTC, amarthadan commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Interesting. I thought it shouldn't be included. Feel free to keep it then.

2022-04-12 06:41 UTC, amarthadan commented on terraform/main.tf
> +      "memory": 512,
I don't have any preference tbh. Let's say 180 just to be on the safe side.

2022-04-12 11:48 UTC, amarthadan requested changes
Looks good, just a few comments :+1:

Can you run all the Terraform files through `terraform fmt` so they have the same formatting? Actually, you can take [`terraform-fmt.ts`](https://github.com/api3dao/airnode/blob/master/scripts/terraform-fmt.ts) from Airnode and add it as a part of the linting process.

You can remove the `outputs.tf` unless we want to have something outputted there.

And I think you can switch from draft to a normal PR at this point :slightly_smiling_face:

2022-04-12 11:48 UTC, amarthadan commented on terraform/network.tf
> +  cidr_block           = "10.0.0.0/16"
Maybe this can be a variable too since all the other IP addresses are.

2022-04-12 11:48 UTC, amarthadan commented on terraform/main.tf
> +  network_configuration {
Don't we need a security group saying that the ECS service can access anything on the internet and nothing can access it from the internet? Have you tried making an HTTP request from inside the container?

2022-04-12 12:39 UTC, acenolaza commented on terraform/main.tf
> +  network_configuration {
This a good point and I wasn't sure so I didn't add it but what you are saying makes sense so I'll check out the docs for security groups and add it.

2022-04-12 12:45 UTC, acenolaza commented
> Looks good, just a few comments +1

I've been running terraform fmt and terraform validate manually but I think it's a good idea to have it as part of the linting process.

> Can you run all the Terraform files through `terraform fmt` so they have the same formatting? Actually, you can take [`terraform-fmt.ts`](https://github.com/api3dao/airnode/blob/master/scripts/terraform-fmt.ts) from Airnode and add it as a part of the linting process.
> 
> You can remove the `outputs.tf` unless we want to have something outputted there.

Right, I thought that I might have a use for it but I'll just remove it for now.

> And I think you can switch from draft to a normal PR at this point slightly_smiling_face

I kept it as a Draft PR because I wasn't sure if airseeker-dev was the right image to use. Also, running `docker pull api3/airseeker-dev:latest` doesn't seem to work for me. I need to use a specific task in order to be able to pull the image from docker hub. Same thing happens when I use `latest` to pull airkeeper image. Maybe @aquarat has any idea what might be happening 🤔 I did found something about having to set some config to true in docker hub in order to be able to pull using `latest`.

2022-04-12 12:54 UTC, amarthadan commented
> I kept it as a Draft PR because I wasn't sure if airseeker-dev was the right image to use. Also, running docker pull api3/airseeker-dev:latest doesn't seem to work for me. I need to use a specific task in order to be able to pull the image from docker hub. Same thing happens when I use latest to pull airkeeper image. Maybe @aquarat has any idea what might be happening thinking I did found something about having to set some config to true in docker hub in order to be able to pull using latest.

I think the problem is that there is no `@api3/airseeker-dev` tagged as `latest` :smile: Set the default to `@api3/airseeker:0.1.0` (even though it doesn't exist yet). You can pass a dev one (with commit hash) as an variable to test that it's actually working.

2022-04-12 21:23 UTC, acenolaza commented on terraform/main.tf
> +  container_definitions = <<DEFINITION
I've just now realized that even though the docker image was being run by ECS the logs were showing some errors white executing the code. These errors are related to the Airseeker code not being able to find the config file. These means that I think I need to make changes to this task definition in order to maybe mount a volume with the config and also add the secret file key pairs as env vars 🤔 

This is the docker command that works for me locally:

```
docker run -it --rm \
--env-file config/secrets.env \
-v "$(pwd)/config:/app/dist/config" \
api3/airseeker:0.1.0
```

would it be a good idea to add it to the README?

2022-04-13 06:32 UTC, amarthadan commented on terraform/main.tf
> +  container_definitions = <<DEFINITION
That is absolutely true, I totally missed that :man_facepalming: The idea was to mount the config directory to `/app/config`. That's on me, I haven't tried the container with the config file being loaded. Set it up for `/app/dist/config` and I'll look into fixing it later.

2022-04-14 06:24 UTC, amarthadan commented on scripts/terraform-fmt.ts
> +import { logger } from '@api3/airnode-utilities';
I used `airnode-utilities` because in Airnode it's already available but if we don't need it here (and I don't think we do) we shouldn't add it just for the logger.

2022-04-14 13:39 UTC, acenolaza commented on scripts/terraform-fmt.ts
> +import { logger } from '@api3/airnode-utilities';
I'll remove it and just use console.log since that's what we are currently doing for the rest of the app. Once we start using a logger then we'll need to come back and make the update.

2022-04-22 13:54 UTC, acenolaza commented
@amarthadan I feel like this is much better now and it's ready for final review.

2022-04-22 13:58 UTC, amarthadan commented
> @amarthadan I feel like this is much better now and it's ready for final review.

Yes, I'll review it later today :slightly_smiling_face:

2022-04-22 19:33 UTC, amarthadan approved these changes
LGTM :muscle: just some small details. I'll try deploying it tomorrow.

2022-04-22 19:33 UTC, amarthadan commented on README.md
> +
Can you maybe add that Docker and Terraform need to be installed on the machine before running this?

2022-04-22 19:33 UTC, amarthadan commented on terraform/main.tf
> +  env_vars = jsonencode([for tuple in regexall("(.*)=(.*)", file(var.app_secrets_file_path)) : { name = tuple[0], value = tuple[1] }])
I'm not a big fan of this but as far as I can tell from googling around it's the only Terraform-only solution. So, yeah, let's start with this and we'll see if we run into some trouble.
Just to be on the safe side, change to regex so that the variable name is not greedy as mentioned on [StackOverflow](https://stackoverflow.com/questions/59789730/how-can-i-read-environment-variables-from-a-env-file-into-a-terraform-script#comment124135133_67653301).

2022-04-22 19:33 UTC, amarthadan commented on terraform/variables.tf
> +  default     = "../config/secrets.env"
Why are these two default paths different? The files are in the same directory, right?

2022-04-22 19:33 UTC, amarthadan commented on terraform/variables.tf
> +}
I think we can have a default value of `dev`, don't you think?

2022-04-24 18:15 UTC, amarthadan commented on docker/Dockerfile.deploy
> +FROM api3/airseeker-dev:${version}
I think instead of having a variable for the version we can have a variable for the full `image:version` string. That way we can have a default for a non-dev image (one that is not released yet) but override it easily during the testing with a development one.

2022-04-24 18:15 UTC, amarthadan commented on terraform/variables.tf
> +}
In the current setup this file path can't be any file path but it needs to be a path within the Docker build context. Which is fine, we can't really do much about it, but there should be a warning that this is the case.

2022-04-24 18:15 UTC, amarthadan commented on terraform/variables.tf
> +}
Also, it needs to be a relative path, not an absolute one. Which is a bit annoying...

2022-04-24 18:15 UTC, amarthadan commented on terraform/variables.tf
> +}
Oh, I understand the difference between the path for `app_config_file_path` and `app_secrets_file_path`. That's really confusing :sweat_smile: Not sure we can do much about it though :confused:

2022-04-24 18:15 UTC, amarthadan commented on terraform/logs.tf
> +}
This looks like it's not used anywhere and I don't see any logs there in AWS either.

2022-04-25 15:00 UTC, acenolaza commented on terraform/variables.tf
> +  default     = "../config/secrets.env"
Yes, the files are in the same directory but the contexts when accessing those files is different. For instance the context when [reading the secrets.env](https://github.com/api3dao/airseeker/blob/adda7568cb25503eff5662bfb3c40cbdd00e346e/terraform/main.tf#L29) is the `/terraform` directory (where `terraform apply` was executed). For the `airseeker.json` file the context is defined in the docker resource [here](https://github.com/api3dao/airseeker/blob/adda7568cb25503eff5662bfb3c40cbdd00e346e/terraform/main.tf#L9) so we don't need to go up a level.

2022-04-25 15:01 UTC, acenolaza commented on terraform/variables.tf
> +}
I like that idea 🤝

2022-04-25 16:03 UTC, acenolaza commented on terraform/logs.tf
> +}
That is weird, I was able to see the logs when clicking on the ECS service link and on the task itself too. There's a Logs tab on both pages or you can open up CloudWatch to see them

2022-04-26 10:22 UTC, amarthadan approved these changes

2022-04-26 10:22 UTC, amarthadan commented on terraform/variables.tf
>  }
I meant that there will be just one variable with a full image name, something like
```terraform
variable "app_docker_image" {
  description = "The docker image to use"
  type        = string
  default     = "api3/airseeker:latest"
}
```

2022-04-26 10:27 UTC, amarthadan commented on terraform/logs.tf
> +}
This is how it looks like
![Screenshot_20220426_122541](https://user-images.githubusercontent.com/1655405/165280075-e64340e0-c98d-4178-8214-d18151d2ad99.png)
The first one is (I guess) automatically created by the container and it contains logs.
The second one is this one from the receipt and is empty. So the logs are there they are just not in this log stream.

2022-04-26 13:26 UTC, acenolaza commented on terraform/logs.tf
> +}
I usually see the log stream in [here](https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/airseeker-mk01-dev-ecs-cluster/services/airseeker-mk01-dev-ecs-service/logs), [here](https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/airseeker-mk01-dev-ecs-cluster/tasks/e7610280db0e402c869b6f57cb727c4b/logs) and/or [here](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/airseeker-mk01-dev-logs/log-events/airseeker-mk01-dev$252Fairseeker-mk01-dev-container$252Fe7610280db0e402c869b6f57cb727c4b).

2022-04-26 13:52 UTC, acenolaza commented on terraform/variables.tf
>  }
Done but caused that I just used 'latest' for the docker image pushed to ECR.

2022-04-26 13:54 UTC, acenolaza commented
I've rebased this branch on top of main and I started getting an issue with the use of `console.log` in `scripts/terraform-fmt.ts` which I fixed by just putting the whole `scripts` folder in the `eslintignore` file because those scripts are only used for development.

2022-04-27 06:57 UTC, amarthadan commented on terraform/logs.tf
> +}
Yes, and the first two links are just reading the logs from the third one. Which is the first one (`airseeker-mk01-dev/airseeker-mk01-dev-container/e7610280db0e402c869b6f57cb727c4b`) on my screenshot. The second one, the one you're creating in recipes (`airseeker-mk01-dev-log-stream`), is not used anywhere. There is also no reference to that resource in recipes. I think you can safely remove it

2022-04-27 07:19 UTC, amarthadan commented on terraform/variables.tf
>  }
Oh, I haven't realized you're using that version someplace else. Hmm :thinking:  The images we're building can be potentially built from the same Airseeker image just with a different configuration file. But the images have unique names, right? You won't overwrite any of these images. So, tagging them as `latest` is imo fine but I would suggest adding a [`LABEL`](https://docs.docker.com/engine/reference/builder/#label) directive storing the Airseeker version and potentially a hash of the configuration file. Something like:
```dockerfile
LABEL airseeker_image=${baseImage} \
      config_sha256=${configHash}
```
Not sure that getting the config file hash will be easy though. Terraform has functions for that but the config file path is Docker context specific not Terraform specific. So, if that would be difficult to do, omit the config file hash for now and add just the Airseeker image.

2022-04-27 14:59 UTC, acenolaza commented on terraform/variables.tf
>  }
Should I try using that hash as the image tag instead of using `latest`? My concern is that using the same Airseeker base image with a different config file will replace the existing image in ECR, right?

2022-04-27 15:41 UTC, amarthadan commented on terraform/variables.tf
>  }
Oh, right, the name is the same. Sorry, I thought that the image is named differently every time the build is run. Never mind then. In that case, you're correct, we should have both the Airseeker image name (the base image) and the hash of the file in the tag. Not sure what characters you can put in the tag though. You won't be able to put a `/` there I presume.
But actually, we don't need to put it solely in the tag, we can name the image as well.
So, if the base image is `api3/airseeker:v0.2` and hash is `1a2b3c` we can name the newly build image `api3/airseeker:v0.2-<hash>`. Would that make sense?

2022-04-27 15:42 UTC, acenolaza commented on terraform/variables.tf
>  }
~I'm thinking that we would have the same issue when creating a images using the same config file but different base image.~

~Currently the ECR docker image name is `repository_url:tag`~

~I wonder if `tag` should be a hash of base image plus config file instead 🤔~

I wrote this message before I saw your last reply and I totally agree with the name structure suggested 👍🏻

2022-04-27 19:00 UTC, acenolaza commented on terraform/variables.tf
>  }
@amarthadan Please review my last commit. I basically created an image tag with the following structure:

`api3-airseeker-dev-0.1.0-b224647`

I've also re-worked the docker context a little bit so we don't need to go up a level in the terraform vars and they both use the same path (secrets and config file)

I've also removed the unused log-stream so I feel like this might be the merge candidate 🤞🏻

2022-04-28 09:31 UTC, amarthadan commented on terraform/variables.tf
>  }
I thought that we will put it in the image name so you don't have to "sanitize" the string but this works as well :slightly_smiling_face: 
I think this is good to go :+1:

2022-04-28 12:01 UTC, acenolaza commented on terraform/variables.tf
>  }
I tried but I got a weird `503 X-Auth `error if I don't remove the `:` and the `/` from the tag name 🤷🏻

2022-04-28 12:02 UTC, merged