[WIP]: Make signed data requests
api3dao/airseeker-v1 pull request #15
Opened 2022-04-08 07:57 UTC by Siegrift

2022-04-12 07:51 UTC, amarthadan requested changes

2022-04-12 07:51 UTC, amarthadan commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
I really don't think we need a new dependency for doing `url + '/' + endpoint` :smile:

2022-04-12 07:51 UTC, amarthadan commented on src/make-request.ts
> +import anyPromise from 'promise.any';
I would actually consider bumping the environment to node 16 so we can use the native [`Promise.any`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any). Or maybe at least using [`core-js`](https://github.com/zloirock/core-js) (which is mentioned in the official documentation), it feels a bit more mature. WDYT?

2022-04-12 07:51 UTC, amarthadan commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
I haven't realized you want to make multiple requests here. Shouldn't we then call the function `makeSignedDataGatewayRequests` instead? Even though it returns just one response...

2022-04-12 07:51 UTC, amarthadan commented on src/validation.ts
> +export const signatureSchema = z.string().regex(/^0x[a-fA-F0-9]+$/);
Aren't these two regexes switched? I would imagine that the signature one will be of a fixed length (64) and that the value one will be of a dynamic length. Correct me if I'm wrong.

2022-04-12 07:51 UTC, amarthadan commented on test/fixtures.ts
> +// Airkeeper with signed data gateway enabled deployed on API3 account which can be used for testing.
I still don't like this and would prefer a mock server. This is nowhere documented, don't know what version of gateway it's running, don't know if I have access to check it if it's down, and so on. The mock server is like 10 lines of code at most.

2022-04-12 07:51 UTC, amarthadan commented on src/make-request.ts
> +): Promise<SignedData | null> => {
Maybe it would make sense to return a different structure than `SignedData`. You'll change the gateway response in [AN-572](https://api3dao.atlassian.net/browse/AN-572) anyway so you can prepare for that here. If we return the new structure here right away we would have to fix just this one function. And the structure itself is kinda weird. `{timestamp: ..., value: ..., signature:...}` would make more sense. WDYT?

2022-04-12 08:48 UTC, Siegrift commented on src/make-request.ts
> +import anyPromise from 'promise.any';
This one is also mentioned there https://github.com/tc39/proposal-promise-any and based on the NPM downloads its fine. I don't think "maturity" context really holds in this case, since it's a single function to be implemented (not an evolving project).

> I would actually consider bumping the environment to node 16

Crossed my mind as well, but we use v14 in all tools and I'd hate switching between the versions.

2022-04-12 08:48 UTC, Siegrift commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
Yeah, we probably should. 

I also dislike the `Gateway` type, which is actually an array of `NotExactlySureHowToNameThis` (but `Gateways` refers to the record of `Gateway`).

2022-04-12 08:48 UTC, Siegrift commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
Maybe: `Gateway`, `Gateways`, `GatewaysRecord` ?

2022-04-12 08:48 UTC, Siegrift commented on src/make-request.ts
> +): Promise<SignedData | null> => {
I'd rather defer that to a separate PR. For now I think saving the gateway response as is is the best suited for this task. For example, we might also store some other data (e.g. which gateway is the response coming from) so this interface might change couple of times.

2022-04-12 08:48 UTC, Siegrift commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
I was actually doing this without the dependency using the https://developer.mozilla.org/en-US/docs/Web/API/URL/URL but it didn't correctly handle a case when the URL didn't end with slash (which took me some time to debug).

After googling it for a few minutes, I am convinced that this is the *currently best* way to do this. without shooting myself into foot.

2022-04-12 08:48 UTC, Siegrift commented on src/validation.ts
> +export const signatureSchema = z.string().regex(/^0x[a-fA-F0-9]+$/);
Beacons data must actually be bytes32 (string length 64) because of this https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/dapis/DapiServer.sol#L883 and for the signature length I am not sure, so I set it to `regex+` (I don't think it matters much).

I think we should require 64 length for the encoded value, but this deserves a comment. WDYT?

2022-04-12 08:48 UTC, Siegrift commented on test/fixtures.ts
> +// Airkeeper with signed data gateway enabled deployed on API3 account which can be used for testing.
> This is nowhere documented, don't know what version of gateway it's running

Yeah, valid points - I think we should document it somewhere. Pinned slack post/confluence? I was thinking this gateway would be common for all api3 dev to play/test with and not only for this test.

> don't know if I have access to check it if it's down, and so on.

Yeah, that is a good point (I personally don't have access).

> The mock server is like 10 lines of code at most.

That little? :D Anyway, such test will test a very limited happy path and the mock server can get out of sync with Airnode. I'd rather treat this Airnode as an "external dependency" and go with this test even though there are these disadvantages. If this turns out to be a problem, we can remove this and implement the mock server. WDYT?

2022-04-12 08:48 UTC, Siegrift commented on test/fixtures.ts
> +// Airkeeper with signed data gateway enabled deployed on API3 account which can be used for testing.
Btw. we are not handling Airnode gateway versions in Airseeker so the following can happen:
a) The gateway request shape changes (e.g. v2 in the URL instead of v1)
b) The gateway response changes (e.g. refactor shape of data)

I don't think we need to care about this atm, but we should in the future. WDYT?

2022-04-12 09:26 UTC, amarthadan commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
You mean...like this? :smile: 
![Screenshot_20220412_112500](https://user-images.githubusercontent.com/1655405/162927729-70b7d001-8dfa-475e-a7f0-639295dfc025.png)

2022-04-12 09:28 UTC, amarthadan commented on src/make-request.ts
> +import anyPromise from 'promise.any';
Fair enough, keep it.

2022-04-12 09:33 UTC, amarthadan commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
Do we actually need that distinction? I think this is the only part of the code that will deal with the `gateways` field. But I'm not against it, it just feels redundant.

2022-04-12 09:35 UTC, amarthadan commented on src/validation.ts
> +export const signatureSchema = z.string().regex(/^0x[a-fA-F0-9]+$/);
> Beacons data must actually be bytes32 (string length 64) because of this https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/dapis/DapiServer.sol#L883

Didn't know that, that's fine then.

> for the signature length I am not sure, so I set it to regex+ (I don't think it matters much).

I think it's the same thing with the signature length. If it is in fact static we should enforce it (make the validation check) the same way we do for the value. We will avoid a potential unnecessary update call.

2022-04-12 09:50 UTC, amarthadan commented on test/fixtures.ts
> +// Airkeeper with signed data gateway enabled deployed on API3 account which can be used for testing.
> That little?

https://github.com/api3dao/airnode/blob/master/packages/airnode-operation/src/server.ts This is 26 and contains logic we don't need so I think I'm pretty close :smile:

> Anyway, such a test will test a very limited happy path and the mock server can get out of sync with Airnode.

But that's true even for the Airnode itself. Even if we release a new Airnode the deployment has to be updated, same as the mock server would need to be updated.

> I'd rather treat this Airnode as an "external dependency" and go with this test even though there are these disadvantages. If this turns out to be a problem, we can remove this and implement the mock server. WDYT?

Let's do it the other way around. Let's start with the mock server (we're doing that for Airnode and Airkeeper at the moment anyway) and we can discuss and plan a proper deployment of a testing environment that will be used in all e2e tests across products. That would be actually neat, having like a real API provider and Airnode running we can make tests against. But at the moment I don't want a few tools using their own mock servers and one tool depending on an external dependency.

2022-04-12 10:21 UTC, Siegrift commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
Yeah, but in nodejs/chrome :D 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/22679154/162939485-e53829e7-9403-4e10-ae11-36fa4f5d95d7.png">

2022-04-12 10:24 UTC, Siegrift commented on test/fixtures.ts
> +// Airkeeper with signed data gateway enabled deployed on API3 account which can be used for testing.
Ok, I'll revert.

2022-04-12 10:31 UTC, Siegrift commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
I'd create a low priority ticket for that, because the config.json schema should be updated as well, WDYT?

2022-04-12 10:33 UTC, Siegrift commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
I will rename `makeSignedDataGatewayRequest` to `makeSignedDataGatewayRequests` but I still dislike that it receives an argument `gateway: Gateway` which is confusing imo.

2022-04-12 10:36 UTC, Siegrift commented on src/validation.ts
> +export const signatureSchema = z.string().regex(/^0x[a-fA-F0-9]+$/);
```
ECDSA signatures in Ethereum consist of three parameters: v , r and s . The signature is always 65-bytes in length. and returns the address used to sign the message.
```

Will set it to 130

2022-04-12 11:07 UTC, amarthadan commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
The fuck? :man_facepalming: 
Fair enough. But I still think this is easy enough problem so we don't need a library.
```ts
let url;
if (gatewayUrl.endsWith('/') {
  url = `${gatewayUrl}${endpointId}`;
} else {
  url = `${gatewayUrl}/${endpointId}`;
}
```
Or is there any other edge case?

2022-04-12 11:10 UTC, amarthadan commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
> I'd create a low priority ticket for that, because the config.json schema should be updated as well, WDYT?

Not really sure what ticket you want to create.

> I will rename makeSignedDataGatewayRequest to makeSignedDataGatewayRequests but I still dislike that it receives an argument gateway: Gateway which is confusing imo.

Kinda. As I said, I'm not against what you're proposing.

2022-04-12 11:14 UTC, Siegrift commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
I am not sure, but probably not. If you rally want it I can use if-else.

2022-04-12 11:16 UTC, amarthadan commented on src/make-request.ts
> +    const fullUrl = urlJoin(url, endpointId);
Yes, please do so :pray:

2022-04-12 12:06 UTC, Siegrift commented on src/make-request.ts
> +export const makeSignedDataGatewayRequest = async (
Let me just do it now, we can drop it (the commit I'll create) if you disagree.

2022-04-13 07:15 UTC, amarthadan approved these changes
Just the two small things and this is good to go :+1:

2022-04-13 07:15 UTC, amarthadan commented on package.json
> +    "pm2:stop:testing-services": "pm2 delete testing-services.config.js",
I know that it's running pm2 but I would name it `dev:something` like we do in the rest. Also, please add separate targets for hardhat and mock server (I personally use those instead :sweat_smile:).

2022-04-13 07:15 UTC, amarthadan commented on package.json
> +    "@types/url-join": "^4.0.1",
You can remove this now, right?

2022-04-13 07:15 UTC, amarthadan commented on test/server.ts
> +});
14 lines and 4 of them empty. 10 exactly! Told you... :joy:

2022-04-13 07:18 UTC, Siegrift commented on test/server.ts
> +});
And x more dependencies and configuration files and package.json scripts :D 

Not even close :D

2022-04-13 07:20 UTC, Siegrift commented on package.json
> +    "pm2:stop:testing-services": "pm2 delete testing-services.config.js",
> Also, please add separate targets for hardhat and mock server (I personally use those instead 😅).

What targets?

2022-04-13 07:21 UTC, amarthadan commented on package.json
> +    "pm2:stop:testing-services": "pm2 delete testing-services.config.js",
https://github.com/api3dao/airkeeper/blob/psp-e2e-test/package.json#L26-L27

2022-04-13 07:48 UTC, Siegrift commented on package.json
> +    "pm2:stop:testing-services": "pm2 delete testing-services.config.js",
Actually I now realized that we do not need hardhat (at least as of now) so I'll remoeve that from the testing services config and only leave API there.

2022-04-13 08:01 UTC, merged