Implemet beacon set updates #166
api3dao/airseeker-v1 pull request #182
Opened 2022-08-02 20:32 UTC by acenolaza

Closes #166 

I tried using the same flow and similar logic used for updating beacon values. This should come handy when working on #167 

I've left a couple of TODOs with some doubts that I have.

This is a draft PR basically because I haven't been able to execute the run-locally.ts script so I need to find a proper way to test these changes locally and also add an e2e test case.

2022-08-03 20:19 UTC, acenolaza commented
While trying to fix the e2e tests, I've realized that it might not be a good idea to run the beacon and beacon-set updates in parallel because we might get nonce errors when using the same sponsor wallet. They seem to be needed to run one after the other.

2022-08-04 05:55 UTC, Siegrift commented
> They seem to be needed to run one after the other.

But how to achieve this? Can't we instead force different sponsor wallets for beacons and beacon sets?

2022-08-04 11:37 UTC, acenolaza commented
> > They seem to be needed to run one after the other.
> 
> But how to achieve this? Can't we instead force different sponsor wallets for beacons and beacon sets?

I'm refactoring the airseeker.json config file where I'm now grouping `beacons` and `beaconSets` triggers by `sponsorWallet`. 

Managing sponsor wallets and keeping the topped up is not a trivial task so I'm not sure if forcing them to use separate sponsor wallets is a good option 🤷🏻

2022-08-04 13:25 UTC, Siegrift commented
> I'm refactoring the airseeker.json config file where I'm now grouping beacons and beaconSets triggers by sponsorWallet.

So they will all have the same `updateInterval ` value, right?

2022-08-04 13:37 UTC, acenolaza commented
> > I'm refactoring the airseeker.json config file where I'm now grouping beacons and beaconSets triggers by sponsorWallet.
> 
> So they will all have the same `updateInterval ` value, right?

Exactly, that's the only "downside" that I've found so far

2022-08-04 13:52 UTC, Siegrift commented
> that's the only "downside" that I've found so far

I don't see a big problem with it. Btw. are you working on https://api3workspace.slack.com/archives/C037NLX1R8T/p1658137012920379?thread_ts=1658072085.473819&cid=C037NLX1R8T as well?

2022-08-04 13:59 UTC, acenolaza commented
> > that's the only "downside" that I've found so far
> 
> I don't see a big problem with it. Btw. are you working on https://api3workspace.slack.com/archives/C037NLX1R8T/p1658137012920379?thread_ts=1658072085.473819&cid=C037NLX1R8T as well?

Yes and I'm about to push a commit with this new refactor (in a separate branch for just in case)
btw, thanks for taking the time to review this PR 🙏🏻

2022-08-11 07:09 UTC, amarthadan requested changes
Looks good :+1: Just some minor issues.

2022-08-11 07:09 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +          ...dataFeedUpdate.beacons.flatMap((b) => b.beaconId),
I think this one doesn't need to be `flatMap` but just `map`, the returning value is a string.

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +  const startTime = Date.now();
Having the `startTime` initialized within `updateBeacons` and `updateBeaconSets` separately effectively doubles the time the processing can take. The start time should be passed to both from the `updateDataFeedsInLoop` function.

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +      if (isNil(beaconResponse)) {
Do we need to use `isNil`? Isn't `if (!beaconValues[beaconId])` enough?

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +        if (isNil(beaconValueOnChain)) {
Same here.

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +      logger.warn('There was an error fetching beacon data for beacon set. Skipping.');
Don't you need to pass the log options so we know what beacon set is this in regard to?

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
Is the beacon set not being initialized a problem? Shouldn't we, in that case, update it to initialize it? @bbenligiray

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +      };
You can move the function outside but I presume you're planning to do that as part of https://github.com/api3dao/airseeker/issues/167

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.ts
> +      // TODO: should we use median like in DapiServer or mean?
I think we should use the same as the contract is using. @bbenligiray

2022-08-11 07:09 UTC, amarthadan commented on src/update-data-feeds.test.ts
> +const cpsbg: ComparableProviderSponsorDataFeeds[] = [
Can you change the variable name accordingly?

2022-08-11 09:11 UTC, bbenligiray commented on src/update-data-feeds.ts
> +      // TODO: should we use median like in DapiServer or mean?
Exact same implementation as the contract

2022-08-11 13:42 UTC, acenolaza commented on src/update-data-feeds.ts
> +      };
Right, I wanted to first confirm this is the right function to call and I also kept is close to where it is being used to make it easier to the reviewer. For now I'll just move it outside this function but I'll keep it in the same file until #167

2022-08-11 13:45 UTC, acenolaza commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
I think it shouldn't be an issue and we should continue to initialize it but this validation [here](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/update-data-feeds.ts#L164-L166) got me confused

2022-08-11 13:56 UTC, acenolaza commented on src/update-data-feeds.ts
> +      logger.warn('There was an error fetching beacon data for beacon set. Skipping.');
Yes,  we do. Good catch!

2022-08-11 14:03 UTC, acenolaza commented on src/update-data-feeds.ts
> +      if (isNil(beaconResponse)) {
I'm using a variable because we are accessing that element in the array a couple of times down below and yes, using `!` instead of `isNil` should have the same effect BUT 🤭 I have trusting issues when it comes to javascript evaluating truthiness for things like empty objects `{}` being truthy, etc but I can stop using `isNil` if there are performance issues or something.

2022-08-11 14:06 UTC, acenolaza commented on src/update-data-feeds.ts
> +  const startTime = Date.now();
Good point 🤔 I wonder if this would be better handled in #167. I'll probably just apply your suggestion for the time being tho

2022-08-15 06:48 UTC, amarthadan commented on src/update-data-feeds.ts
> +      if (isNil(beaconResponse)) {
Not a performance issue really. It just threw me off seeing using `isNil` and `!` for essentially the same check (one in `updateBeacons` and one in `updateBeaconSets`). I would just like to keep it consistent.

2022-08-15 07:09 UTC, amarthadan approved these changes

2022-08-15 14:13 UTC, acenolaza commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
@bbenligiray any comments around this TODO?

2022-08-16 09:26 UTC, bbenligiray commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
I'm not sure what validation you're referring to but I don't see any reason to not initialize it

2022-08-16 12:15 UTC, acenolaza commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
I was referring to the check for an onchain value in order to update a beacon [here](https://github.com/api3dao/airseeker/blob/main/src/update-beacons.ts#L151).

2022-08-16 12:49 UTC, bbenligiray commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
There are three things that may happen
- Successfully read an initialized data feed with a value and non-zero timestamp (an return the value)
- Successfully read an uninitialized data feed with zero value and zero timestamp (and return the value)
- Fail reading the data feed

The problem here is that when `readOnChainBeaconData()` returns zero, you won't know if the data feed is initialized or not. Normally it should initialize the data feed no matter what the deviation is. Note that `readOnChainBeaconData()` returning `null` doesn't mean that it's not initialized. Also that function should probably be called `readOnChainDataFeed()`.

2022-08-16 13:12 UTC, acenolaza commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
Right, the issue is not around the data feed being initialized or not but instead checking if Airseeker is able to read the data feed onchain value or not.

Meaning that if [beaconSetValueOnChain](https://github.com/api3dao/airseeker/blob/202434c52b341b2842bc6a7ecdeb48596090dca7/src/update-data-feeds.ts#L372) is `null` then there was probably an unexpected issue that prevented Airseeker from reading the onchain value (provider error, msg.sender not being whitelisted, etc). 

So the questions is: should we proceed with the update if Airseeker failed to read the onchain value? or just continue with the next `beaconSet` (like when updating beacons)?

2022-08-16 14:26 UTC, bbenligiray commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
Ah sorry, I thought this was about initialization. If the returned value is `null` we should skip it.

2022-08-16 14:29 UTC, acenolaza commented on src/update-data-feeds.ts
> +    // Should we continue with next beaconSet? See https://github.com/API3-CTT/airseeker/blob/166-update-beacon-sets-implementation/src/update-beacons.ts#L151
Cool, thanks 🙏🏻  and no need to apologize since I introduced the confusion by talking about the value not being initialized in the TODO comment.

2022-08-17 12:24 UTC, merged