Remove unnecesary parts
api3dao/airseeker-v1 pull request #205
Opened 2022-08-19 06:46 UTC by amarthadan

Close #162

I'm pretty sure all this can be removed but whoever will be reviewing this, please, read it carefully :smile:

I also fixed the tests not passing when the project is built before running them (we don't do that in the CI, but it's quite common for a local setup) in the first commit.

2022-08-22 14:45 UTC, Siegrift reviewed
Some minor comments, but 👍 LGTM.
I'll try to test this (and only give approve after I've seen it work).

2022-08-22 14:45 UTC, Siegrift commented on README.md
> +1. Deploy Airseeker using and start the new Airseeker immediately using the invoke commands below.
```suggestion
1. Deploy Airseeker using WHAT and start the new Airseeker immediately using the invoke commands below.
```

2022-08-22 14:45 UTC, Siegrift commented on README.md
> +1. Deploy Airseeker using and start the new Airseeker immediately using the invoke commands below.
same below

2022-08-22 14:45 UTC, Siegrift commented on README.md
> +2. Deploy Airseeker using and wait up to 14 minutes for the deployed Airseeker to start.
Mhhh, why 14?

2022-08-22 14:45 UTC, Siegrift commented on test/tsconfig.json
> +  "extends": "../tsconfig.json",
Nit: We might want to get rid of the TS config base (inline it similarly to how its done in Airnode).

Leaving that up to you.

2022-08-22 14:45 UTC, Siegrift commented on README.md
> +that both Airseekers can run concurrently. Wait for the new Airseeker to start. Once it does, ensure that you're
How can you tell if the second one works correctly? 

The onchain updates could be done by the first (older) Airseeker. You can check on AWS whether the new Airseeker is running fine, though.

2022-08-22 19:19 UTC, acenolaza commented on .gitignore
> +# Ignore dist build folder in every (sub)folder
```suggestion
# Ignore dist and build folder in every (sub)folder
```

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +2. Deploy Airseeker using and wait up to 14 minutes for the deployed Airseeker to start.
Probably because of [this](https://github.com/api3dao/airseeker/blob/59dac797f8148c56945a509fd8514be213f93a9b/serverless.aws.yml#L27)

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +1. Deploy Airseeker using and start the new Airseeker immediately using the invoke commands below.
```suggestion
1. Deploy Airseeker and start the new Airseeker immediately using the invoke commands below.
```

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +2. Deploy Airseeker using and wait up to 14 minutes for the deployed Airseeker to start.
```suggestion
2. Deploy Airseeker and wait up to 14 minutes for the deployed Airseeker to start.
```

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +Export AWS credentials in your terminal or ensure your local aws installation is logged in.
Should we point to some aws or api3 docs where we mention which vars we are talking about? (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +yarn sls deploy --region us-east-1 --config serverless.aws.yml
Is the `--region` arg needed here in order to override [this](https://github.com/api3dao/airseeker/blob/59dac797f8148c56945a509fd8514be213f93a9b/serverless.aws.yml#L11) value?

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +yarn sls remove
Don't you need to also give it the `--config` arg value?

2022-08-22 19:19 UTC, acenolaza commented on README.md
> +If an Airseeker is already deployed, deploy the new Airseeker using a different service name in `serverless.yaml`, so
I wonder if one can do this by just using a different `stage` value in serverless.yaml 🤔

2022-08-22 19:29 UTC, acenolaza commented
[This](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/scripts/run-locally.ts#L0-L1) script might also not make sense now that the idea is to use serverless invoke to run Airseeker locally, right?

2022-08-23 06:15 UTC, amarthadan commented on README.md
> +yarn sls deploy --region us-east-1 --config serverless.aws.yml
Yes.

2022-08-23 06:19 UTC, amarthadan commented on README.md
> +yarn sls remove
I was wondering about that as well and according to the [documentation](https://www.serverless.com/framework/docs/providers/aws/cli-reference/remove), there's no `--config` option for the `remove` command. But I've just double-checked it in the actual CLI and the option is available. I'll add it.

2022-08-23 07:58 UTC, amarthadan commented
> [This](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/scripts/run-locally.ts#L0-L1) script might also not make sense now that the idea is to use serverless invoke to run Airseeker locally, right?

`serverless invoke` will invoke the deployed Lambda function, it doesn't run the code locally.

2022-08-23 08:07 UTC, amarthadan commented on README.md
> +Export AWS credentials in your terminal or ensure your local aws installation is logged in.
I don't think we actually have a good section about this in the docs. There are mentions about the `aws.env` file (https://docs.api3.org/airnode/v0.7/reference/examples/aws-env.html, https://docs.api3.org/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/#aws-env) but it feels like it would be more confusing than helpful.

2022-08-23 12:55 UTC, acenolaza commented
> > [This](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/scripts/run-locally.ts#L0-L1) script might also not make sense now that the idea is to use serverless invoke to run Airseeker locally, right?
> 
> `serverless invoke` will invoke the deployed Lambda function, it doesn't run the code locally.

I'm a bit confused now 🤭 wouldn't this work for running it locally? `yarn sls invoke local --config serverless.aws.yml -f airseeker`

2022-08-23 13:27 UTC, amarthadan commented
> > > [This](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/scripts/run-locally.ts#L0-L1) script might also not make sense now that the idea is to use serverless invoke to run Airseeker locally, right?
> > 
> > 
> > `serverless invoke` will invoke the deployed Lambda function, it doesn't run the code locally.
> 
> I'm a bit confused now hand_over_mouth wouldn't this work for running it locally? `yarn sls invoke local --config serverless.aws.yml -f airseeker`

Oh, I haven't realized there's a `local` option, sorry. Yes, in that case the script and the `start` target don't need to be there. I'll remove it.

2022-08-24 18:07 UTC, acenolaza approved these changes
LGTM 👍🏻

2022-08-24 19:45 UTC, Siegrift requested changes
Running locally via `yarn sls invoke local --config serverless.aws.yml -f airseeker` fails for me with:
```
$ /Users/emanueltesar/vacuumlabs/api3/airseeker/node_modules/.bin/sls invoke local --config serverless.aws.yml -f airseeker
✖ Error: Cannot find module '/Users/emanueltesar/vacuumlabs/api3/airseeker/dist/serverless'
...
```

the problem is that the `/dist` folder has the sources wrapped in `src` folder. Changing serverless config path [here](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/serverless.aws.yml#L21) helps, but we get another error:
```
Error:
Error: Failed to parse config file. Error: ENOENT: no such file or directory, open '/Users/emanueltesar/vacuumlabs/api3/airseeker/dist/config/airseeker.json'
...
```

since the config dir is not included in dist.

2022-08-25 12:36 UTC, amarthadan commented
> Running locally via `yarn sls invoke local --config serverless.aws.yml -f airseeker` fails for me with:
> 
> ```
> $ /Users/emanueltesar/vacuumlabs/api3/airseeker/node_modules/.bin/sls invoke local --config serverless.aws.yml -f airseeker
> ✖ Error: Cannot find module '/Users/emanueltesar/vacuumlabs/api3/airseeker/dist/serverless'
> ...
> ```
> 
> the problem is that the `/dist` folder has the sources wrapped in `src` folder. Changing serverless config path [here](https://github.com/api3dao/airseeker/blob/remove-unnecesary-parts/serverless.aws.yml#L21) helps, but we get another error:
> 
> ```
> Error:
> Error: Failed to parse config file. Error: ENOENT: no such file or directory, open '/Users/emanueltesar/vacuumlabs/api3/airseeker/dist/config/airseeker.json'
> ...
> ```
> 
> since the config dir is not included in dist.

Good catch! There were multiple issues actually. Should be fixed now.

2022-08-25 13:26 UTC, Siegrift approved these changes
Works for me locally.

2022-08-25 16:56 UTC, acenolaza commented
Something that I find a bit strange is that after running `yarn build` we get a `/build` and a `/dist` folders in the root. Shouldn't we only have one or the other? (I see that `src-tsconfig.tsbuildinfo` file is being put inside `/build` on purpose)

2022-08-26 06:07 UTC, amarthadan commented
> Something that I find a bit strange is that after running `yarn build` we get a `/build` and a `/dist` folders in the root. Shouldn't we only have one or the other? (I see that `src-tsconfig.tsbuildinfo` file is being put inside `/build` on purpose)

@Siegrift will know better, so, correct me if I'm wrong but I think `/build` is for building all the source files so they are typechecked and `/dist` contains only what we would package in the NPM package.

2022-08-26 06:36 UTC, Siegrift commented
> @Siegrift will know better, so, correct me if I'm wrong but I think /build is for building all the source files so they are typechecked and /dist contains only what we would package in the NPM package.

Exactly.

2022-08-26 09:53 UTC, merged