Add deviation check
api3dao/airseeker-v1 pull request #26
Opened 2022-04-13 09:13 UTC by vponline

This adds the functionality to check the DapiServer value for a **beaconId** and check if the updated API value deviation passes the deviationThreshold.

2022-04-13 09:17 UTC, vponline commented on test/check-condition.feature.ts
> +const dapiServerAbi = JSON.parse(fs.readFileSync(path.resolve('./src/test/artifacts/DapiServer.json')).toString());
I used these tests to check that this actually worked with the Airkeeper DapiServer local PSP setup, and these could be used for E2E tests in the future. Otherwise I can delete if these are not needed.

2022-04-13 12:55 UTC, vponline commented on src/check-condition.ts
> +};
Do we want a `try-catch` here for `readDataFeedValueWithId`?

2022-04-13 13:18 UTC, bbenligiray commented on src/check-condition.ts
> +};
I assume you need to read the full data feed including the timestamp in Airseeker because it will need to update based on timestamp whatever the value is

2022-04-13 13:47 UTC, vponline commented on src/check-condition.ts
> +};
:+1: Fixed. 

In this case, should I create a new function to read the value if it's needed in other places as well? Or will the timestamp logic be added here?

2022-04-13 16:04 UTC, bbenligiray commented on src/check-condition.ts
> +};
We shouldn't do multiple calls to the blockchain provider to read the same value. @amarthadan can comment on how that should be implemented.

2022-04-13 16:57 UTC, acenolaza reviewed
A few comments but overall is looking good 👍🏻

2022-04-13 16:57 UTC, acenolaza commented on src/check-condition.test.ts
> +  let dapiServerMock: any;
Should we try to set proper types here?

2022-04-13 16:57 UTC, acenolaza commented on src/check-condition.ts
> +  const voidSigner = new ethers.VoidSigner(ethers.constants.AddressZero, provider);
These 2 seems like they should be initialized only once instead of doing it for every condition check.

2022-04-13 16:57 UTC, acenolaza commented on src/check-condition.ts
> +  updatedApiValue: number
Nit: just apiValue maybe? or mostUpToDateApiValue? or latestApiValue? or just keep current 😁

2022-04-13 16:57 UTC, acenolaza commented on src/check-condition.ts
> +  const dapiServerResponse = await dapiServer.connect(voidSigner).readDataFeedWithId(beaconId);
Maybe here we might want to just return `true` if current datafeed timestamp value is older than x amount of time? WDYT @bbenligiray and skip the condition check?

2022-04-13 18:06 UTC, acenolaza commented on src/check-condition.ts
> +  return (change.toNumber() / HUNDRED_PERCENT) * 100;
I have a really hard time trusting integers in js and I wonder if we should just keep doing the math using BigNumber instead 🤔

2022-04-14 07:20 UTC, vponline commented on src/check-condition.ts
> +  return (change.toNumber() / HUNDRED_PERCENT) * 100;
That makes sense to me now that you mentioned :smile:

2022-04-14 07:45 UTC, amarthadan commented on src/check-condition.ts
> +};
@bbenligiray Do you mean if different sponsors (on the same chain) want to read the same beacon? I'm not sure how that can be easily done since you can configure different update intervals for each sponsor. Or am I missing something?

Or do you mean the same chain, the same sponsor, and multiple providers?

2022-04-14 07:47 UTC, amarthadan commented on src/check-condition.ts
> +  const voidSigner = new ethers.VoidSigner(ethers.constants.AddressZero, provider);
Yes, what's @acenolaza saying is true. You can expect the provider (an initialized provider object) to be passed to the function.

2022-04-14 08:08 UTC, amarthadan commented on src/check-condition.ts
> +  const dapiServerResponse = await dapiServer.connect(voidSigner).readDataFeedWithId(beaconId);
That's going to be added as part of the [BEC-297](https://api3dao.atlassian.net/browse/BEC-297).

2022-04-14 10:59 UTC, vponline commented on src/check-condition.ts
> +  const voidSigner = new ethers.VoidSigner(ethers.constants.AddressZero, provider);
Then we can just pass in the voidSigner right? We don't need the provider itself.

2022-04-14 13:25 UTC, Siegrift requested changes

2022-04-14 13:25 UTC, Siegrift commented on src/check-condition.test.ts
> +describe('calculateUpdateInPercentage', () => {
I don't think we need so many tests. I'd drop the `calculates increase` and  `calculates decrease` since they are implicitely tested by the other ones.

2022-04-14 13:25 UTC, Siegrift commented on src/check-condition.test.ts
> +    const readDataFeedWithIdMock = (_beaconId: string) => Promise.resolve([ethers.BigNumber.from(500)]);
Nit: you don't need to specify arguments if you don't need to use them.

2022-04-14 13:25 UTC, Siegrift commented on src/check-condition.test.ts
> +        ...dapiServerMock,
Why can't you do the same mocking as in the beforeEach hook? I think it would be a bit cleaner not to use the beforeEach and mock `dapiServerMock` in each of the tests.

2022-04-14 13:25 UTC, Siegrift commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
Mhh, I wonder if this edge case should be explained somewhere (for the API integrators).

2022-04-14 13:25 UTC, Siegrift commented on src/check-condition.ts
> +  const [dapiServerValue, _timestamp] = await dapiServer.connect(voidSigner).readDataFeedWithId(beaconId);
We also want to to update if the response is too old (not sure if that is part of this task though)

2022-04-14 13:25 UTC, Siegrift commented on test/check-condition.feature.ts
> +  const dapiServer = new ethers.Contract('0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0', DapiServerFactory.abi, provider);
1) I am missing scripts to deploy this contract
2) This test is not seem to be recognized by jest configuration.
3) Can you rename the `e2e.test.ts` to `make-request.feature.ts`? Also, maybe put them into folder `e2e`.

2022-04-15 06:16 UTC, vponline commented on test/check-condition.feature.ts
> +  const dapiServer = new ethers.Contract('0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0', DapiServerFactory.abi, provider);
I will cover all of these in the Airseeker E2E task.

(if you wanted to run these you could deploy the Airkeeper local PSP + run the update script).

2022-04-15 06:17 UTC, vponline commented on src/check-condition.ts
> +  const [dapiServerValue, _timestamp] = await dapiServer.connect(voidSigner).readDataFeedWithId(beaconId);
Will be covered in another task :smile:

2022-04-15 10:14 UTC, vponline commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
What kind of case were you thinking? (I thought this is just a math limitation)

2022-04-15 12:53 UTC, acenolaza approved these changes

2022-04-16 13:16 UTC, Siegrift commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
> (I thought this is just a math limitation)

It is, but we have to handle it somehow and using 1 seems the best we could do.

> What kind of case were you thinking?

If the value was `0` and now is `5` it doesn't make sense to ask "how big is the deviation" (because there is the division by 0). We divide by 1 in that case, which seems reasonable but it behaves strangely since deviation from 0 -> 1 leads the same percentage update as 1 -> 2.

2022-04-16 13:17 UTC, Siegrift commented on test/check-condition.feature.ts
> +  const dapiServer = new ethers.Contract('0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0', DapiServerFactory.abi, provider);
I think at least this test should be included in the pipeline before the PR is merged.

2022-04-16 13:18 UTC, Siegrift reviewed
👍 The functionality LGTM, but I think the e2e test should be included in the pipeline.

2022-04-18 06:07 UTC, vponline commented on test/check-condition.feature.ts
> +  const dapiServer = new ethers.Contract('0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0', DapiServerFactory.abi, provider);
Ok, I can add the setup for these from the E2E branch :smile:

2022-04-18 07:19 UTC, vponline commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
> We divide by 1 in that case, which seems reasonable but it behaves strangely since deviation from 0 -> 1 leads the same percentage update as 1 -> 2.

Shouldn't this be fine as the result is that the beacon should be updated? The actual update percentage doesn't really matter in this case (when the **dapiServerValue** is 0), right? Perhaps @amarthadan can comment as well.

(For context, this function is essentially the same as the smart contract function [here](https://github.com/api3dao/airnode/blob/v1-protocol/packages/airnode-protocol-v1/contracts/dapis/DapiServer.sol#L862))

2022-04-19 05:40 UTC, Siegrift commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
Yeah, the value is 0 initially, so after the first beacon update should always update the value on chain. 
However, the value *could* be also set to 0 by the API and it's not clear whether the next non zero value should also trigger update. But this is an edge case, which I can't imagine happening in practice, so I think the implementation is good.

2022-04-19 05:53 UTC, Siegrift approved these changes
👍 LGTM

2022-04-19 05:53 UTC, Siegrift commented on test/config/config.ts
> +export const buildAirseekerConfig = () => ({
It would be better to move this to `test/fixtures`

2022-04-19 05:53 UTC, Siegrift commented on test/setup/deployment.ts
> +// TODO uncomment once airnode-node 0.6 is released
Nit: (more like my ocd :D)

```
TODO: uncomment...
```

2022-04-19 05:53 UTC, Siegrift commented on tsconfig.json
> +  "include": ["./src/**/*.ts", "./test/**/*", "./hardhat.config.ts"],
This is OK for now, but we should have two separate tsconfigs (one for development and one for prod), but this is tracked in https://api3dao.atlassian.net/browse/BEC-311

2022-04-20 07:09 UTC, amarthadan approved these changes
I'm approving this but please take a look at my comments before merging.

2022-04-20 07:09 UTC, amarthadan commented on .github/workflows/main.yml
> +
Is this actually faster than having it run after the unit tests? If so, I'm ok with it but you need to add the `if` key to stop tests from running twice for PRs and you need to remove `yarn dev:testing-services:start` from the `lint-build-test` job above.

2022-04-20 07:09 UTC, amarthadan commented on package.json
> +    "dev:clean": "rimraf -rf ./logs",
Why do we even create the `./logs` directory? If it's just for tests can't we log either to STDOUT or `/dev/null` or turn it off altogether if we don't need it?

2022-04-20 07:09 UTC, amarthadan commented on src/check-condition.ts
> +  const absoluteInitialValue = initialValue.isZero() ? ethers.BigNumber.from(1) : initialValue.abs();
I agree with both of you. I think we should follow the implementation from the contract and I agree that this implementation is fine.

2022-04-20 07:09 UTC, amarthadan commented on tsconfig.json
> +  "include": ["./src/**/*.ts", "./test/**/*", "./hardhat.config.ts"],
Why do we need this? Tests are actually excluded in https://github.com/api3dao/airseeker/pull/28 to make the build process work correctly.

2022-04-20 08:51 UTC, vponline commented on package.json
> +    "dev:clean": "rimraf -rf ./logs",
These were removed form Airkeeper as well so I'll remove

2022-04-20 09:01 UTC, vponline commented on .github/workflows/main.yml
> +
I dont believe it is faster, I'll change it to run after the unit tests (like you had done in beacon-updates)

2022-04-20 09:53 UTC, merged