Allow creation of airseeker configuration
api3dao/airseeker-v1 pull request #264
Opened 2022-10-07 04:20 UTC by Ashar2shahid

part of refactoring operations is to migrate the creation scripts away from operations and into the respective repositories. With this script it should be easy to create airseeker config scripts based on operations data.

2022-10-10 14:15 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +          },
I think that this changes is required to satisfy latest validation schema 😸 
```suggestion
          options: {
            fulfillmentGasLimit: 500000,
            gasPriceOracle: [
              {
                gasPriceStrategy: 'latestBlockPercentileGasPrice',
                percentile: 60,
                minTransactionCount: 20,
                pastToCompareInBlocks: 20,
                maxDeviationMultiplier: 2,
              },
              {
                gasPriceStrategy: 'providerRecommendedGasPrice',
                recommendedGasPriceMultiplier: 1.2,
              },
              {
                gasPriceStrategy: 'constantGasPrice',
                gasPrice: {
                  value: 10,
                  unit: 'gwei',
                },
              },
            ],
          },
```

2022-10-10 14:16 UTC, bdrhn9 commented on package.json
> +    "dev:create-operations-config": "ts-node scripts/create-airseeker-config.js",
```suggestion
    "dev:create-operations-config": "ts-node scripts/create-airseeker-config.ts",
```

2022-10-10 14:20 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +  };
`updatedOpsData` is not used later so it can be deleted. Btw, it would be better to have deployment folder imo.

2022-10-10 14:21 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +    },
If `updatedOpsData` is going to be deleted, this question will be also redundant.

2022-10-10 14:25 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +  const operationsRepository = readOperationsRepository(operationRepositoryTarget);
Maybe another question can be added that asks `operationRepositoryTarget` for creating config from whether remote or local files. Totally optional 😸

2022-10-10 14:31 UTC, bdrhn9 requested changes
After zod validator satisfied, LGTM 🔥

2022-10-10 23:34 UTC, Ashar2shahid commented on scripts/create-airseeker-config.ts
> +  const operationsRepository = readOperationsRepository(operationRepositoryTarget);
yeah I added this for airkeeper but I was wondering if its needed for airseeker. I added it in with the other PR fixes

2022-10-12 09:01 UTC, aquarat commented
If @bdrhn9 is happy I'm happy (thanks for reviewing). Although as you noted some of this work will be made redundant by the ops repo migration to a database.

2022-10-12 10:53 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +  );
```suggestion
  const airseekerBeacons = beacons.reduce(
    (beaconObj, beacon) => ({
      ...beaconObj,
      [beacon.beaconId]: {
        airnode: beacon.airnodeAddress,
        templateId: beacon.templateId,
        fetchInterval: Math.ceil(
          Math.min(
            ...Object.values(beacon.chains)
              .filter((chain) => 'airseekerConfig' in chain)
              .map((chain) => chain.airseekerConfig!.updateInterval)
          ) / 2
        ),
        fetchMethod: 'gateway',
      },
    }),
    {} as Beacons
  );
```

2022-10-12 10:54 UTC, bdrhn9 commented on scripts/create-airseeker-config.ts
> +  };
```suggestion
  const airseeker = {
    airseekerWalletMnemonic: '${AIRSEEKER_WALLET_MNEMONIC}',
    log: airseekerLogs,
    beacons: airseekerBeacons,
    beaconSets: airseekerBeaconSet,
    chains: airseekerChains,
    gateways: airseekerGateways,
    templates: aiseekerTemplates,
    triggers: airseekerTriggers,
    endpoints: {},
    ois: [],
    apiCredentials: [],
  };
```

2022-10-12 10:58 UTC, bdrhn9 approved these changes
After merging #257, latest suggestions needs to be committed for backward compatibility. I tested this changes, feel free to commit them 👍🏼 
As a note, with these suggestions, this scripts only works for fetching via gateways. For newly added direct call method, functions that prepare `endpoints`, `ois`, and `apiCredentials` needs to be added. I think it's going to be easy, because we already implemented them for Airkeeper. Issue can be created for this situation.

2022-10-25 07:29 UTC, Ashar2shahid commented
I didn't realize I hadn't merged this yet 🤦 . Applied the PR suggestions that bedrihan suggested and he's right we can create new issue to add the new endpoints

2022-10-25 07:30 UTC, merged