BEC-315:Fix where's the configuration loaded from in the container
api3dao/airseeker-v1 pull request #28
Opened 2022-04-15 16:59 UTC by acenolaza

I ended up moving the src folder out of dist folder inside the container to match the path of `__dirname` value when running Airseeker locally using `yarn start`

2022-04-15 17:00 UTC, acenolaza commented on tsconfig.json
> +    "outDir": "./dist"
This is to fix this issue: https://api3workspace.slack.com/archives/C037NLX1R8T/p1649954030733229

2022-04-19 07:09 UTC, amarthadan requested changes
This won't work because you won't be able to run pm2 locally.

The ideal solution would be to build everything directly into a `dist` directory. That way we can point everything to `dist/main.js` and the program will look for the config file in `${__dirname}/../config/airseeker.json` and will find it.

Problem is that currently when you run `yarn build` the `dist` directory contains `src` directory (instead source files directly) and `test` directory. I don't really know why the `test` directory is included but once removed I think it will build directly into `dist` which will solve the problem.

2022-04-19 11:28 UTC, acenolaza commented
> This won't work because you won't be able to run pm2 locally.

Right, I only tested `yarn start` script when testing locally

> The ideal solution would be to build everything directly into a `dist` directory. That way we can point everything to `dist/main.js` and the program will look for the config file in `${__dirname}/../config/airseeker.json` and will find it.
> 
> Problem is that currently when you run `yarn build` the `dist` directory contains `src` directory (instead source files directly) and `test` directory. I don't really know why the `test` directory is included but once removed I think it will build directly into `dist` which will solve the problem.

Thanks for the feedback. Let me try this approach then 👍🏻

2022-04-19 14:18 UTC, amarthadan approved these changes
LGTM :+1:

2022-04-19 14:18 UTC, amarthadan commented on tsconfig.json
> +  "exclude": ["node_modules", "src/**/*.test.ts", "dist/**/*"]
Interesting. I didn't think about removing test files from `src`. I guess it was including the `test` directory because some tests (in `src`) load fixtures from there. But I think you should be able to remove the `"dist/**/*"` part.

2022-04-19 15:40 UTC, acenolaza commented on tsconfig.json
> +  "exclude": ["node_modules", "src/**/*.test.ts", "dist/**/*"]
Correct. There were tests importing fixtures causing the folder structure (`src` and `test`) to be created inside `dist`. I can remove the `"dist/**/*"` part but I just wanted to be consistent with Airkeeper build [tsconfig.json](https://github.com/api3dao/airkeeper/blob/main/tsconfig-build.json) file. Should I still remove it?

2022-04-20 06:28 UTC, amarthadan commented on tsconfig.json
> +  "exclude": ["node_modules", "src/**/*.test.ts", "dist/**/*"]
Feel free to leave it there but I don't think it does anything since the `outDir` is set to `./dist` and the whole `dist` directory is always removed before the build :man_shrugging:

2022-04-20 13:51 UTC, acenolaza commented on tsconfig.json
> +  "exclude": ["node_modules", "src/**/*.test.ts", "dist/**/*"]
Then I guess we should remove it in both places 😁

2022-04-20 20:24 UTC, merged