Add E2E tests
api3dao/airseeker-v1 pull request #31
Opened 2022-04-18 12:56 UTC by vponline

This adds E2E tests for Airseeker.

2022-04-21 11:27 UTC, vponline commented
This is ready for review. Sorry about the mess with commits :facepalm:, it should be quite straight forward to go through the file changes, though.

2022-04-21 11:29 UTC, vponline commented on src/index.ts
> +main();
I had to move this into a separate file so that it wouldn't run immediately when `main` is imported into test files.

2022-04-21 11:31 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +      await sleep(25_000);
These make the tests quite long, but seem to be necessary for all the cycles to finish in time in the Github environment.

2022-04-21 12:01 UTC, Siegrift commented on .github/workflows/main.yml
> +      - name: Run testing services
Does this matter? :D

2022-04-21 12:01 UTC, Siegrift commented on package.json
> +    "test:e2e": "SILENCE_LOGGER=true jest --selectProjects e2e --runInBand"
`--runInBand` will make the tests run sequentially (slower). Is it needed?

2022-04-21 12:01 UTC, Siegrift commented on src/main.ts
> +  console.log('Stopping Airseeker...');
We always seek more :D

2022-04-21 12:01 UTC, Siegrift commented on test/setup/deployment.ts
> +    // node.evm.
?

2022-04-21 12:14 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +      await sleep(25_000);
I tried with sub 10 second times, but it just wasn't finishing in time on Github, I can experiment a bit more :smile:

2022-04-21 12:15 UTC, vponline commented on .github/workflows/main.yml
> +      - name: Run testing services
Probably not? :thinking:

2022-04-21 12:17 UTC, vponline commented on package.json
> +    "test:e2e": "SILENCE_LOGGER=true jest --selectProjects e2e --runInBand"
Yes we need to re-deploy all contracts and set the initial beacon states (after the hardhat network is reset with `hardhat_reset`) before each test so this ensures that those happen sequentially.

2022-04-21 12:18 UTC, vponline commented on test/setup/deployment.ts
> +    // node.evm.
This can be uncommented once Airnode v0.6 is available and we can use `deriveSponsorWalletFromMnemonic` from the package

2022-04-21 12:42 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +      await sleep(25_000);
Nice it seems to work with 10 seconds, and 8 and 6 seconds for the intervals. I also tried with 6 seconds but that failed.

2022-04-22 07:22 UTC, Siegrift requested changes
👍 Code LGTM, but the the test are taking too long and we are mostly waiting. I think that should be improved.

After I ran `yarn` my `yarn.lock` file is different. Is it just me?

2022-04-22 07:22 UTC, Siegrift commented on test/fixtures/config.ts
> +      fetchInterval: 8,
Why can't we make it  `0.5` here? Or something even lower?

2022-04-22 07:22 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +    await sleep(3_000);
Why is this needed?

2022-04-22 07:22 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +      await sleep(10_000);
This is too long imo, and since the test run sequentially we are mostly just waiting. I think sleeping for a second should be enough when the update/fetch intervals are shorter.

2022-04-22 07:25 UTC, Siegrift commented
I tried decreasing all the timers and it passes for me locally: https://github.com/api3dao/airseeker/commit/83d772cb229f555358b13e2c51aa361e0b1c2591

2022-04-22 07:33 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +    await sleep(3_000);
This was added to make sure that the signed data request timestamps will be valid once updating the beacon. Otherwise I was getting an '`Fulfillment older than beacon`' error.

2022-04-22 07:40 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +    expect(beaconValueETHNew).toEqual(hre.ethers.BigNumber.from(723.39202 * 1_000_000));
I think it would be nicer to compare that the values before equals the value after.

2022-04-22 07:40 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +    await sleep(3_000);
Mhh, I was not getting this error when I disabled this wait time and ran the test locally 🤔 . But can't you make the server return more future timestamps instead of this waiting?

2022-04-22 07:45 UTC, vponline commented on test/fixtures/config.ts
> +      fetchInterval: 8,
The validator expects these to be integers. 1 second intervals work locally for me too, but it just doesn't seem to work in the Github environment (i think their machines are slower).

2022-04-22 07:46 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +    await sleep(3_000);
> But can't you make the server return more future timestamps instead of this waiting?

Yes this works too if that's preferred :smile:

2022-04-22 07:54 UTC, Siegrift commented
> Mhh, I was not getting this error when I disabled this wait time and ran the test locally 🤔 . But can't you make the server return more future timestamps instead of this waiting?

Ignore this. I tried rerunning this and it doesn't work for me either...

2022-04-22 08:03 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +      await sleep(25_000);
Yeah, I get the same results now. I don't have any ideas how to speed it up further :/

2022-04-22 08:04 UTC, Siegrift commented on test/fixtures/config.ts
> +      fetchInterval: 8,
Yeah, and it doesn't work because the blockchain calls will surely timeout...

2022-04-22 08:05 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +    await sleep(3_000);
It will save 3 seconds for every test so I think it's worth it.

2022-04-22 08:09 UTC, Siegrift commented on test/e2e/airseeker.feature.ts
> +import * as hre from 'hardhat';
You can add `import '@nomiclabs/hardhat-ethers'` and it will resolve the TS errors.

2022-04-22 13:33 UTC, amarthadan commented on src/index.ts
> +main();
Don't forget to change references in Dockerfile, package.json, etc. from `main.ts/js` to `index.ts/js`.

2022-04-22 13:33 UTC, amarthadan commented on test/mock-utils.ts
> +// NOTE: This file is referenced as a pathGroup pattern in .eslintrc (import/order)
We already have this function in `src/config.test.ts`. Can you remove it from there?

2022-04-22 13:33 UTC, amarthadan commented on src/make-request.ts
> +        headers: { 'x-api-key': apiKey, 'Content-Type': 'application/json' },
This is not a part of this PR, is it?

2022-04-22 13:33 UTC, amarthadan commented on test/e2e/airseeker.feature.ts
> +      await sleep(10_000);
So, how many cycles is that? It looks a bit high just for one.

2022-04-23 09:06 UTC, vponline commented on src/make-request.ts
> +        headers: { 'x-api-key': apiKey, 'Content-Type': 'application/json' },
No, but it is needed for the mock server to parse the `req.body` correctly

2022-04-23 09:41 UTC, vponline commented on test/e2e/airseeker.feature.ts
> +      await sleep(10_000);
I lowered the sleep to 8 seconds (lowering to 5 second sleep and 4 second intervals failed). It's 1 cycle before stopping, and then waiting for 1 more. Lower intervals and sleep times just don't seem to finish on time in Github (locally you can do 1-2 seconds).

2022-04-25 09:09 UTC, Siegrift approved these changes
👍 code LGTM, but the tests are failing

2022-04-26 09:57 UTC, amarthadan commented
@vponline Can you maybe rebase so there are not 111 commits in this PR? :sweat_smile:

2022-04-26 11:50 UTC, vponline commented
> @vponline Can you maybe rebase so there are not 111 commits in this PR? sweat_smile

Fixed, sorry about that :sweat_smile:

2022-04-27 07:29 UTC, amarthadan approved these changes
LGTM :+1:

2022-04-27 07:40 UTC, merged