Use only unquoted secrets for Airseeker
api3dao/airseeker-v1 pull request #57
Opened 2022-04-28 09:29 UTC by amarthadan

Having two different versions of the secrets file is quite annoying so I updated the `run-locally.sh` file to deal with unquoted secrets since that format is required by both Docker and our Terraform recipes.

Can somebody test it on Mac though? :smile: 

Tagging @aquarat and @Ashar2shahid to let you know that this is the format that will be needed for deployment.

2022-04-28 10:37 UTC, Siegrift requested changes
Unfortunately, does not work for me :/ (tried both bash and zsh).
When I do `yarn start`:
```
$ scripts/run-locally.sh ts-node src/index.ts
/Users/emanueltesar/vacuumlabs/api3/airseeker/scripts/../config/secrets.env
grep -v ^\s*# /Users/emanueltesar/vacuumlabs/api3/airseeker/scripts/../config/secrets.env
scripts/run-locally.sh: line 12: syntax error near unexpected token `('
error Command failed with exit code 2.
```

I tried to debug this a bit, but I am not sure why it happens. When I do:
```
cat <(grep -v "^\s*#" /Users/emanueltesar/vacuumlabs/api3/airseeker/scripts/../config/secrets.env | sed 's/\([^=]*\)=\(.*\)/\1=\"\2"/')
```

it works. Do we need this to be a shell script? I think it would be easier to make this a node script instead? Or use https://github.com/google/zx

You also want to change the `docker:run` command.

2022-04-28 10:37 UTC, Siegrift commented on config/secrets.example.env
> +# Secrets passed to dockerized Airseeker must NOT be quoted.
```suggestion
# Airseeker secrets must NOT be quoted.
```

2022-04-28 10:37 UTC, Siegrift commented on scripts/run-locally.sh
> +SECRETS_FILE=$(dirname $(readlink -f "$0"))/../config/secrets.env
I realized we want to add the fail immediatelly flag `set -e` (https://intoli.com/blog/exit-on-errors-in-bash-scripts/)

2022-05-05 13:02 UTC, amarthadan commented
@Siegrift I switched to `bash` can you try it now?

2022-05-05 20:19 UTC, Siegrift commented
Unfortunately it still doesn't work for me. 

When I do `yarn start` it starts the app, however the secrets are not passed correctly and I receive validation error `Error: Error interpolating secrets. Make sure the secrets format is correct. ReferenceError: AIRSEEKER_WALLET_MNEMONIC is not defined`. I've checked and `AIRSEEKER_WALLET_MNEMONIC` is defined in secrets, but undefined in Airseeker.

It seems the `source` command doesn't work properly, because the the secret is undefined even when I do `echo $AIRSEEKER_WALLET_MNEMONIC`

2022-05-10 06:41 UTC, amarthadan commented
Ok, this doesn't lead anywhere. @Siegrift can you take over this? It makes no sense for me to come up with a solution that might work on mac :smile: And I'm pretty sure that whatever will eventually work on mac will work on linux as well.

2022-05-10 15:36 UTC, Siegrift commented
Will do.

2022-05-17 11:28 UTC, Siegrift commented
@amarthadan I've implemented it using JS as it was the fastest way to get this done. It seems to be working on my side.

2022-05-17 12:50 UTC, amarthadan commented on package.json
> +    "pm2:start": "ts-node -T scripts/run-locally.ts pm2 start airseeker-service.config.js",
Why would you add the `-T` option? That's skipping the type checking, right?

2022-05-17 12:55 UTC, amarthadan commented on scripts/run-locally.ts
> +import { parse } from 'dotenv';
This is such a heavy-weight solution for such a tiny problem. Adding two more libraries, running node and TS and manually reading the secrets and adding the quotes :see_no_evil: I know none of that matters in this case but it's horrible :see_no_evil: My solution was so elegant. Stupid Mac... :sob:

2022-05-17 12:57 UTC, Siegrift commented on package.json
> +    "pm2:start": "ts-node -T scripts/run-locally.ts pm2 start airseeker-service.config.js",
Yes, but it's faster. I think that is more important.

2022-05-17 12:57 UTC, Siegrift commented on scripts/run-locally.ts
> +import { parse } from 'dotenv';
I disliked your solution :p :D

2022-05-17 13:00 UTC, amarthadan commented on package.json
> +    "pm2:start": "ts-node -T scripts/run-locally.ts pm2 start airseeker-service.config.js",
Yeah, I'd say we want the type check pretty much all the time.

2022-05-17 13:29 UTC, Siegrift approved these changes
I've tested it both locally and using docker and got the same behaviour, and both seem to be working fine.

2022-05-17 13:30 UTC, Siegrift commented on package.json
> +    "pm2:start": "ts-node -T scripts/run-locally.ts pm2 start airseeker-service.config.js",
The scripts will be typechecked once https://github.com/api3dao/airseeker/pull/102 is merged.

2022-05-17 13:46 UTC, merged