Add check that the signed data are not older than data on-chain
api3dao/airseeker-v1 pull request #58
Opened 2022-04-28 19:15 UTC by Siegrift

Add check that the signed data are not older than data on-chain

2022-05-03 07:20 UTC, vponline approved these changes
Nice :+1:

2022-05-03 07:20 UTC, vponline commented on src/check-condition.ts
> +  return parseInt(signedData.data.timestamp, 10) > onChainData.timestamp;
Just curious what is the 10 radix doing here? If the timestamp is already `Math.floor`-ed in Airnode?

Mostly asking in case we need to add it somewhere else as well. :thinking:

2022-05-03 07:31 UTC, Siegrift commented on src/check-condition.ts
> +  return parseInt(signedData.data.timestamp, 10) > onChainData.timestamp;
I need `parseInt` to convert that to a number. In JS a radix should always (as a good practice) be used because radix 10 is not a default. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

2022-05-03 12:15 UTC, amarthadan requested changes
I like the extraction of reading the on-chain value from `checkUpdateCondition` :+1:

2022-05-03 12:15 UTC, amarthadan commented on src/update-beacons.ts
> +export const readOnChainBeaconData = async (
Can you follow the convention of other functions that the function is not returning the "go" result but an actual value or `null`?

2022-05-03 12:15 UTC, amarthadan commented on src/check-condition.ts
> +}
Nit. Can you move the interface above the function? I think it's better for readability (or at least it helps me :sweat_smile:)

2022-05-03 12:15 UTC, amarthadan commented on src/check-condition.ts
> +  onChainData: OnChainBeaconData,
Why do you pass the whole `OnChainBeaconData` object if we don't care about the timestamp? You can pass just the value itself.

2022-05-03 12:15 UTC, amarthadan commented on src/check-condition.ts
> +export const checkSignedDataFreshness = (onChainData: OnChainBeaconData, signedData: SignedData) => {
Again, why pass the whole thing, we need just a timestamp.

2022-05-03 12:15 UTC, amarthadan commented on src/check-condition.ts
> +export const checkSignedDataFreshness = (onChainData: OnChainBeaconData, signedData: SignedData) => {
And this one is especially confusing because you're passing two different structures but you're picking just timestamps from them.

2022-05-03 12:24 UTC, vponline commented on src/check-condition.ts
> +  onChainData: OnChainBeaconData,
We (will) need `timestamp` for #60 (but I guess it depends on who merges first :smile: )

2022-05-03 12:34 UTC, amarthadan commented on src/check-condition.ts
> +  onChainData: OnChainBeaconData,
I reacted in https://github.com/api3dao/airseeker/pull/60#discussion_r863726412

2022-05-04 10:40 UTC, Siegrift commented on src/update-beacons.ts
> +export const readOnChainBeaconData = async (
Sure.

2022-05-04 10:41 UTC, Siegrift commented on src/check-condition.ts
> +}
https://www.youtube.com/watch?v=Y0pdQU87dc8

2022-05-04 10:47 UTC, Siegrift commented on src/check-condition.ts
> +export const checkSignedDataFreshness = (onChainData: OnChainBeaconData, signedData: SignedData) => {
It is not that confusing to me. The `updateBeacons` functions is complex and it's doing a lot more then it should. I am delegating that part of the logic to this helper function.

2022-05-04 10:52 UTC, Siegrift commented on src/check-condition.ts
> +export const checkSignedDataFreshness = (onChainData: OnChainBeaconData, signedData: SignedData) => {
But It is now inconsistent with the other functions so I'll update it.

2022-05-05 07:09 UTC, amarthadan approved these changes

2022-05-05 07:09 UTC, amarthadan commented on src/check-condition.ts
> +};
I'm wondering if this function even makes sense since it's just one comparison. Maybe we should just do that directly in `updateBeacons`. But that's just a nit, I'm ok with having it here.

2022-05-05 07:11 UTC, Siegrift commented on src/check-condition.ts
> +};
It is easier to test this way. It's better to keep it imo.

2022-05-05 10:39 UTC, merged