BEC-363: Implement configurable logging
api3dao/airseeker-v1 pull request #73
Opened 2022-05-02 16:07 UTC by acenolaza

Re-used the Airnode logger structure of using `meta` and `additional`.

2022-05-03 08:25 UTC, amarthadan requested changes
I have two concerns:
* We're a bit inconsistent in what's considered a warning and what error. Are we considering warning to be everything that doesn't stop the Airseeker? Because due to the design that's almost everything. I don't mind we should just clarify the intentions.
* I think we shouldn't use `log()` when we're using `warn()`, `debug()`, etc. We should instead use `info()` to be explicit.

2022-05-03 08:25 UTC, amarthadan commented on src/check-condition.ts
> +  const logOptionsBeaconId = { additional: { 'Beacon-ID': beaconId, 'Dapi-Server': dapiServer.address } };
I think we would need to add chain ID as well because you can have the same beacon ID and dapi server address on multiple chains (I think). You don't need to add it here (as we don't have it available) but I think https://github.com/api3dao/airseeker/pull/58 changes the structure a bit and it will become easy to add. Just add a TODO for now.

2022-05-03 08:25 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +import { shortenAddress, sleep } from './utils';
Why did the order change? If your editor is doing this automatically please, turn it off because it's creating these unnecessary changes.

2022-05-03 08:25 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
What's the difference between `meta` and `additional`?

2022-05-03 08:25 UTC, amarthadan commented on src/logging.ts
> +  airnodeLogger.debug(message, merge({ ...getState().logOptions }, logOptionsOverride));
Do we actually need the `merge` function? If I understand it correctly, `LogOptionsOverride` can have only `meta` and `additional` properties. We don't have these in the state log options. So, simple
```ts
{...getState().logOptions, ...logOptionsOverride}
```
should be enough.

2022-05-03 08:25 UTC, amarthadan commented on src/state.ts
> +      { coordinatorId: randomHexString(16) }
I'm fine with this even though this will change only when the Airseeker is restarted which shouldn't happen very often. But I would name it differently, what about `airseekerId`?

2022-05-03 08:25 UTC, amarthadan commented on src/update-beacons.ts
> +      logger.log(`Deviation threshold not reached. Skipping.`, logOptionsBeaconId);
What level is `log()` logging under?

2022-05-03 08:25 UTC, amarthadan commented on src/update-beacons.ts
> +    logger.warn(
This is definitely not a warning :sweat_smile:

2022-05-03 08:25 UTC, amarthadan commented on src/validation.ts
> +    logLevel: logLevelSchema,
Maybe it would be better to have one `logging` or `log` section and having `format` and `level` there:
```json
{
  "log": {
    "format": "plain",
    "level": "INFO"
  }
}
```

2022-05-03 12:50 UTC, acenolaza commented
> I have two concerns:
> 
> * We're a bit inconsistent in what's considered a warning and what error. Are we considering warning to be everything that doesn't stop the Airseeker? Because due to the design that's almost everything. I don't mind we should just clarify the intentions.

That is exactly right. At least that was how I approach it in Airkeeper but I'm open to comments and suggestions. That is also why there are just a few `logger.error` in the code where we are just throwing and stopping the Airseeker execution.

> * I think we shouldn't use `log()` when we're using `warn()`, `debug()`, etc. We should instead use `info()` to be explicit.

Completely agree. That was my mistake.

2022-05-03 12:51 UTC, acenolaza commented on src/update-beacons.ts
> +    logger.warn(
🤦🏻‍♂️ 😁  good catch!

2022-05-03 12:52 UTC, acenolaza commented on src/update-beacons.ts
> +      logger.log(`Deviation threshold not reached. Skipping.`, logOptionsBeaconId);
I should have switched it to `info()`

2022-05-03 12:59 UTC, acenolaza commented on src/state.ts
> +      { coordinatorId: randomHexString(16) }
Right, I faced this same limitation in Airkeeper. The problem is that [buildBaseOptions](https://github.com/api3dao/airnode/blob/master/packages/airnode-utilities/src/logging/logging.ts#L11-L17) is a function imported from the airnode-utilities package and it creates a `LogOptions` object which only has `coordinatorId`. We might want to make it more dynamic on the [airnode-utilities type](https://github.com/api3dao/airnode/blob/master/packages/airnode-utilities/src/logging/types.ts#L6). Something like `readonly [key:string]:string` or maybe just `readonly processId:string`

2022-05-03 13:01 UTC, acenolaza commented on src/logging.ts
> +  airnodeLogger.debug(message, merge({ ...getState().logOptions }, logOptionsOverride));
I started by doing that but then I realized I didn't want to override the fields currently in `meta` and `additional` child objects so that is why I decided to do a deep merge and only add instead of replace.

2022-05-03 13:02 UTC, acenolaza commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
[additional](https://github.com/api3dao/airnode/blob/master/packages/airnode-utilities/src/logging/types.ts#L14) seems to be more flexible since it is of type `any`

2022-05-03 13:03 UTC, acenolaza commented on src/fetch-beacon-data.ts
> +import { shortenAddress, sleep } from './utils';
I'm doing that manually by clicking shift+alt+o to remove any unused import that I might have added while writing the code. I'll stop doing that if it's an issue.

2022-05-03 13:04 UTC, acenolaza commented on src/check-condition.ts
> +  const logOptionsBeaconId = { additional: { 'Beacon-ID': beaconId, 'Dapi-Server': dapiServer.address } };
I'll add the TODO then

2022-05-05 08:09 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
I see :confused: I think we will eventually change that in Airnode as it's currently built mainly for Airnode and doesn't really fit the other tools we're building. I would actually ignore the `meta` object entirely and add everything to the `additional`. That way, once we generalize that on Airnode (which I think will lead to keeping just one field) we'll easily switch. WDYT? I presume the way it's logged, the actual output, is the same for `meta` and `additional` right?

2022-05-05 08:10 UTC, amarthadan commented on src/logging.ts
> +  airnodeLogger.debug(message, merge({ ...getState().logOptions }, logOptionsOverride));
But that's what I'm saying. The logging options in the state don't have `meta` and `additional` fields so it should be safe to concat them just by spreading.

2022-05-05 08:21 UTC, amarthadan commented
> That is exactly right. At least that was how I approach it in Airkeeper but I'm open to comments and suggestions. That is also why there are just a few `logger.error` in the code where we are just throwing and stopping the Airseeker execution.

I'm fine with this approach, just wanted to make sure :slightly_smiling_face:

2022-05-05 08:53 UTC, amarthadan requested changes

2022-05-05 08:53 UTC, amarthadan commented on src/make-request.ts
>      }
Even though this one, and the other two below, are throwing errors, if you look at [`fetchBeaconData`](https://github.com/api3dao/airseeker/blob/main/src/fetch-beacon-data.ts#L87) you'll see that they are handled and Airseeker is not stopping. So, I think, those should be just warnings.

2022-05-05 14:07 UTC, acenolaza commented on src/check-condition.ts
> +  const logOptionsBeaconId = { additional: { 'Beacon-ID': beaconId, 'Dapi-Server': dapiServer.address } };
Since #58 has been merged I'll look into this now and hopefully remove the TODO

2022-05-05 14:10 UTC, acenolaza commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
Right, the actual output doesn't care if a value is inside `meta` or inside `additional` but WDYT if I just add `airseekerId` to additional and keep using `chainId` and `providerName` from meta (since those are probably not going to change)?

2022-05-05 14:34 UTC, acenolaza commented on src/logging.ts
> +  airnodeLogger.debug(message, merge({ ...getState().logOptions }, logOptionsOverride));
Currently I'm setting the `coordinatorId` in `state.meta` when calling the [airnode-utitilities.buildBaseOptions](https://github.com/api3dao/airseeker/blob/db2518caa8161874afa15708ceed56e507a87d82/src/state.ts#L37) function that initializes the `meta` object. If we stop using `meta.coordinatorId` then we could just use spread operator instead of lodash.merge like you are suggesting so I think there should be no problems to switch to that.

2022-05-05 17:29 UTC, acenolaza commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
Actually, I just found that airnode-utilities logger expects to have something in meta object when setting additional, otherwise get a comma at the beginning like this: 
![image](https://user-images.githubusercontent.com/5776880/166978975-67781d65-9fbd-4683-9161-4b4d0ea2b7e6.png)
because of [this](https://github.com/api3dao/airnode/blob/master/packages/airnode-utilities/src/logging/logging.ts#L114) line in the reduce function.

My suggestion is to keep using meta.coordinatorId until we make changes to the logging.ts file to support apps other than Airnode.

2022-05-10 08:06 UTC, amarthadan commented on src/fetch-beacon-data.ts
> +            additional: { Sponsor: shortenAddress(sponsorAddress) },
I agree, let's do that.

2022-05-10 08:07 UTC, amarthadan commented on src/logging.ts
> +  airnodeLogger.debug(message, merge({ ...getState().logOptions }, logOptionsOverride));
You're right, I'm just blind, carry on :sweat_smile:

2022-05-10 08:23 UTC, amarthadan approved these changes
I think we don't need to do anything about the `meta` vs `additional` issue at the moment. I'm fine with the current state. Fix that one info/error issue and feel free to merge.

2022-05-10 08:23 UTC, amarthadan commented on src/update-beacons.ts
> +    logger.info('No beacons for processing found. Stopping.');
This should be logged as an error.

2022-05-10 12:56 UTC, merged