Add gas oracle for providers
api3dao/airseeker-v1 pull request #75
Opened 2022-05-05 08:19 UTC by vponline

This adds a gas oracle for each chain-provider pair in `airseeker.json`.

1. The oracles will run on a loop based on an `updateInterval` config option.
2. In each loop the oracles will fetch a maximum of `sampleBlockCount` blocks.
  2.1. With the conditions that empty blocks are skipped and already fetched blocks (i.e. already in state) are not re-fetched
3. Calculate the Pth (`percentile`) `percentileGasPrice` and save it in state

Unit/e2e tests to be added later in this PR or in new PRs

2022-05-05 08:28 UTC, vponline commented on config/airseeker.example.json
>        }
I put the config at the chain level, but we could do per provider configuration as well if needed. WDYT?

2022-05-05 08:30 UTC, vponline commented on src/gas-oracle.ts
> +};
@bbenligiray  Do we want something fancier here instead of just returning the `gasPrice` at the Pth percentile?

2022-05-05 08:31 UTC, vponline commented on src/gas-oracle.ts
> +        (tx) => (tx.gasPrice || latestBlock.baseFeePerGas?.add(tx.maxPriorityFeePerGas!))!
Based on the discussion with @aquarat in slack, even EIP1559 chains seem to have the `gasPrice` field but I added `baseFeePerGas + maxPriorityFeePerGas` as backup.

2022-05-05 09:26 UTC, bbenligiray commented
As a note, the transaction contents of block #1234 may have changed since `updateInterval` ago because of something like a reorg. Therefore, this approach uses an approximate gas price history. This is fine for our purposes, but we should be aware in case we want to use the same history for another purpose.

2022-05-05 12:41 UTC, vponline commented on src/gas-oracle.ts
> +    onAttemptError: (goError) => logger.log(`Failed attempt to get block. Error: ${goError.error}`),
I still need to add retry options here. Should we go with the same settings as the current `getGasPrice` (i.e. `prepareGoOptions(startTime, totalTimeout)`)?

2022-05-07 15:56 UTC, vponline commented on src/gas-oracle.ts
> +    onAttemptError: (goError) => logger.log(`Failed attempt to get block. Error: ${goError.error}`),
I added these and moved `prepareGoOptions` to utils

2022-05-13 22:10 UTC, acenolaza requested changes
The code comments are really helpful for reading the code 👏🏻 You may want to consider adding a description about the new config options in the README.

2022-05-13 22:10 UTC, acenolaza commented on src/constants.ts
> +export const DEFAULT_BACK_UP_GAS_PRICE_GWEI = 10;
I might be wrong but adding the `DEFAULT_` prefix might be not consistent with the other consts which are also used as default config values.

2022-05-13 22:10 UTC, acenolaza commented on src/update-beacons.test.ts
> -    expect(api.calculateTimeout(startTime, totalTimeout)).toEqual(2000);
This test and the one in line 254 seem like they need to be moved to a utils.test.ts file

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  logger.log(`Initiating gas oracles`);
We have stopped using `logger.log` and you should now start sending a logOptions object as a second arg to logger functions.

You can check gas-prices.ts or any other file to use as reference.

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  const backupGasPriceGwei = gasOracleConfig?.backupGasPriceGwei || DEFAULT_BACK_UP_GAS_PRICE_GWEI;
A small improvement could be to do this only once per chain instead of per provider since the config is set per chain.

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  logger.log(`Fetching blocks on chain with ID ${chainId} for provider with name ${providerName}`);
You may want to reword these error messages once `chainId` and `providerName` are added to the `logOptions` object

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +    updateBackupGasPrice(chainId, providerName, gasPrice || maxFeePerGas);
Could ethers ever return both `gasPrice` and `maxFeePerGas`? I ask because we might need to read the `chains.options.txType` config option to determine which value to use.

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +    latestBlock.number - latestBlockNumberInState <= sampleBlockCount
Is it possible that the `latestBlock.number` might be the same as the `latestBlockNumberInState` 🤔 If so then `blockCountToFetch` might be 0

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +        (tx) => (tx.gasPrice || latestBlock.baseFeePerGas?.add(tx.maxPriorityFeePerGas!))!
I guess here we should use ! instead of ?, right?

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  while (newBlockData.length < blockCountToFetch) {
Should we just use <= to get rid of lines 183-190?

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  while (newBlockData.length < blockCountToFetch) {
Nit: we could maybe also use a for loop in order to avoid creating a `loopIndex` var

2022-05-13 22:10 UTC, acenolaza commented on src/gas-oracle.ts
> +  const index = Math.ceil(array.length * (percentile / 100)) - 1;
I wonder if there's some library that we can use here 🤔 Probably not one that supports `ethers.BigNumber[]` 😁 

A few things that worry me are:
1. can percentile be 0?
2. can array be empty?

2022-05-14 16:22 UTC, bbenligiray commented on config/airseeker.example.json
>        }
Chain level imo, same as the old gas price parameters

2022-05-14 16:23 UTC, bbenligiray commented on src/gas-oracle.ts
> +};
No, this is fine. Array can be empty though?

2022-05-14 16:26 UTC, bbenligiray commented
This is simpler to implement, but is it possible to not have an `updateInterval` parameter and only update the gas price oracle if there is a transaction to be made?

2022-05-16 09:37 UTC, vponline commented
> This is simpler to implement, but is it possible to not have an `updateInterval` parameter and only update the gas price oracle if there is a transaction to be made?

I don't see why this wouldn't also work. Should I make the changes?

2022-05-16 09:59 UTC, vponline commented on src/gas-oracle.ts
> +  const index = Math.ceil(array.length * (percentile / 100)) - 1;
> Probably not one that supports ethers.BigNumber

Yep, otherwise there are quite a few library options. I took the implenentation from here: [percentile](https://github.com/d4rkr00t/percentile/blob/master/scripts/percentile-baseline.js). (Although without all the number checks that it has :sweat_smile:)

> A few things that worry me are:
> 1. can percentile be 0?
> 2. can array be empty?

Good points! In practice, the code shouldn't go this far if it fails to get `blockData` (and go into the fallback gasPrice if-block) so it should never have an empty array or a percentile of 0, but you're right in that I should address these cases in the function. I think we can return null for these.

2022-05-16 10:15 UTC, vponline commented on src/gas-oracle.ts
> +  while (newBlockData.length < blockCountToFetch) {
> Should we just use <= to get rid of lines 183-190?

Hmm I may not understand what you mean, but wouldn't this re-fetch the 'latest' block?

2022-05-16 10:35 UTC, vponline commented on src/gas-oracle.ts
> +    latestBlock.number - latestBlockNumberInState <= sampleBlockCount
Yep and then it shouldn't proceed to fetch more blocks, although it will return from the function in this case from line 168:

`if (latestBlockInStateMatch) {...}`

But do you see a potential issue with this logic? :thinking:

2022-05-16 10:35 UTC, bbenligiray commented
> I don't see why this wouldn't also work. Should I make the changes?

I think so. Keeping a gas price oracle ready to go in case we need to make a transaction is not useful because it goes stale so fast. For the same reason, we don't really want to use a 15 second-old gas price esitmation.

2022-05-16 10:53 UTC, vponline commented on src/gas-oracle.ts
> +    updateBackupGasPrice(chainId, providerName, gasPrice || maxFeePerGas);
I tried this on a few chains and it actually always returns both (even if it's an EIP1559 network). It seems that `gasPrice` is always returned and could only be `null` if there is an error.

My understading was that we want to always use the (legacy) gasPrice value so I only added the `|| maxFeePerGas` in case ethers has an error getting the gas price. Please let me know if you had another thought though. 

Here's the `ethers.getFeeData()` function for reference of how they implement it:

```ts
async getFeeData(): Promise<FeeData> {
        const { block, gasPrice } = await resolveProperties({
            block: this.getBlock("latest"),
            gasPrice: this.getGasPrice().catch((error) => {
                // @TODO: Why is this now failing on Calaveras?
                //console.log(error);
                return null;
            })
        });

        let maxFeePerGas = null, maxPriorityFeePerGas = null;

        if (block && block.baseFeePerGas) {
            // We may want to compute this more accurately in the future,
            // using the formula "check if the base fee is correct".
            // See: https://eips.ethereum.org/EIPS/eip-1559
            maxPriorityFeePerGas = BigNumber.from("1500000000");
            maxFeePerGas = block.baseFeePerGas.mul(2).add(maxPriorityFeePerGas);
        }

        return { maxFeePerGas, maxPriorityFeePerGas, gasPrice };
    }
```

2022-05-16 15:21 UTC, acenolaza commented on src/gas-oracle.ts
> +    updateBackupGasPrice(chainId, providerName, gasPrice || maxFeePerGas);
I see, so we don't really care what the user sets in airseeker.json config `chains.<id>.options.txType` and we just try to always use gasPrice even for EIP1559 chains, right?

2022-05-16 15:28 UTC, acenolaza commented on src/gas-oracle.ts
> +    latestBlock.number - latestBlockNumberInState <= sampleBlockCount
Right, I missed that if statement. My bad 🙏🏻

2022-05-16 15:32 UTC, acenolaza commented on src/gas-oracle.ts
> +  while (newBlockData.length < blockCountToFetch) {
Correct. I got confused 👍🏻

2022-05-16 15:39 UTC, vponline commented on src/gas-oracle.ts
> +    updateBackupGasPrice(chainId, providerName, gasPrice || maxFeePerGas);
Yes this was my understanding, but another point I missed is whether we want to specify the `txType` as 0 in update-beacons.ts (if we don't the transaction may be still sent as `type 2` on some chains (at least on polygon?)).

2022-05-16 16:12 UTC, acenolaza commented on src/gas-oracle.ts
> +    updateBackupGasPrice(chainId, providerName, gasPrice || maxFeePerGas);
I would (hardcode it probably) but I'm now also wondering why need to have that setting in the config if it has no use 🤔. Should we use `legacy` as default value but keep letting the user change the `txType` via config?

2022-05-17 10:00 UTC, vponline commented on src/gas-oracle.ts
> +};
I have replaced the interval cycle with this `getGasPrice` method which will start fetching block data (and still re-use from state if it's up-to-date) and finally return a gas price.

2022-05-17 16:37 UTC, vponline commented
Fetching 20 blocks (mainnet) is taking 20+ seconds so getting blocks sequentially like this won't do. I'll try out a few options to get the block data in parallel. This will require a provider subscription for use though... :thinking:

2022-05-20 06:10 UTC, vponline commented
I have updated the Gas Oracle implementation:

The gas oracle will fetch the latest and latest - 20 blocks and get the specified percentile from each block. The latest block's percentile will be used if the difference between the two percentiles does not exceed the gasDeviationThreshold.

getGasPrice will be used as a fallback if the gasDeviationThreshold is exceeded, either block has less than minBlockTransactions or failing to fetch either block.

The backupGasPriceGwei config option will be used if failing to fetch both blocks and the fallback gasPrice.

2022-05-20 08:18 UTC, vponline commented on src/check-condition.ts
>    );
I realized this is no longer an async function as we no longer read the DapiServerValue inside it so I updated it since I am re-using it for the gas-oracle.

2022-05-20 15:51 UTC, bbenligiray commented
I'd recommend something like this
```
"options": {
  "txType": "0",
  "gasOracle": {
    "fallbackGasPrice": {
      "value": 10,
      "unit": "gwei"
    },
    "recommendedGasPriceMultiplier": 1.2,
    "latestGasPriceOptions": {
      "percentile": 60,
      "minTransactionCount": 10,
      "pastToCompareInBlocks": 20,
      "maxDeviationMultiplier": 2
    }
  },
  "fulfillmentGasLimit": 500000
}
```
where the "gas oracle" is something that gives you a legacy gas price. `recommendedGasPriceMultiplier` and `latestGasPriceOptions` are optional.
1. Calculates the 60th percentile from the current block (go to 4 if it has less than 10 transactions)
2. Calculates the 60th percentile from 20 blocks ago (go to 4 if it has less than 10 transactions)
3.  If `gaspricenow/2 < gasprice20blocksago > gaspricenow*2` returns `gaspricenow`
4. Call `getGasPrice()` (go to 6 if it fails)
5. Return the recommended gas price times `recommendedGasPriceMultiplier`
6. Return `fallbackGasPrice`

2022-05-23 09:50 UTC, vponline commented
> I'd recommend something like this
> ...
> 1. Calculates the 60th percentile from the current block (go to 4 if it has less than 10 transactions)
> 2. Calculates the 60th percentile from 20 blocks ago (go to 4 if it has less than 10 transactions)
> 3. If `gaspricenow/2 < gasprice20blocksago > gaspricenow*2` returns `gaspricenow`
> 4. Call `getGasPrice()` (go to 6 if it fails)
> 5. Return the recommended gas price times `recommendedGasPriceMultiplier`
> 6. Return `fallbackGasPrice`

I have now updated the gas oracle and tests according to the specs above.

2022-05-27 11:28 UTC, amarthadan requested changes
I haven't reviewed tests yet as I suspect some changes in functionality. I'll do that once those are sorted out.

2022-05-27 11:28 UTC, amarthadan commented on config/airseeker.example.json
> +        "txType": "legacy",
So, what was the result regarding the transaction type discussion?

2022-05-27 11:28 UTC, amarthadan commented on src/gas-prices.ts
> +  chainOptions: node.ChainOptions & { gasPriceMultiplier?: number },
I might be just blind, but I don't see you passing `gasPriceMultiplier` anywhere in the code to the `getGasPrice` function. Actually, I don't see you using our `getGasPrice` (the one from this file, not the one on the RPC provider instance) anywhere. Do we not need this anymore or is that just a mistake?

2022-05-27 11:28 UTC, amarthadan commented on src/gas-prices.test.ts
> +                  gasPriceMultiplier,
There's no such field in the config file as far as I can tell.

2022-05-27 11:28 UTC, amarthadan commented on src/gas-prices.test.ts
> +    const stateSpy = jest.spyOn(state, 'getState');
Can't you just add another chain to the `createMockState` output instead of this?

2022-05-27 11:28 UTC, amarthadan commented on src/gas-prices.ts
> +  gasPrice.mul(BigNumber.from(Math.round(gasPriceMultiplier * 100))).div(BigNumber.from(100));
The same function is also defined in `gas-oracle.ts`. It should be defined only in one place.

2022-05-27 11:28 UTC, amarthadan commented on src/utils.ts
> +// TODO: Errors are not displayed with this approach. Problem?
This TODO doesn't apply anymore and can be removed.

2022-05-27 11:28 UTC, amarthadan commented on test/e2e/airseeker.feature.ts
> -  it('updates the beacons successfully with one invalid provider present', async () => {
Why was this removed?

2022-05-27 11:28 UTC, amarthadan commented on README.md
> +- `maxTimeout`: (optional) - The maximum timeout (in seconds) for fetching a block or fallback gas price (defaults to
Do we need this configurable? We already have a similar timeout for fetching data from an HTTP gateway and that one is hardcoded.

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +        block.data.transactions.map((tx) => (tx.gasPrice || block.data.baseFeePerGas!.add(tx.maxPriorityFeePerGas!))!)
Are these exclamation points ok? Are those values always available? Why are they as optional in ethers?

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +  if (blockPercentileGasPrices.length > 1) {
Isn't this going to be always 2 (or fewer) blocks? We're doing it only for the latest block and the one in history, don't we?

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +    // Return latest the percentile for the latest block if within the limit
```suggestion
    // Return the percentile for the latest block if within the limit
```

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +      sortedBlockPercentileGasPrices[0].percentileGasPrice,
Maybe instead of accessing the values via indices every time we can extract them to variables so it's obvious what those values are. Something like `latestPercentileGasPrice` and `referencePercentileGasPrice`.

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +    // Use the hardcoded back if back up if gasTarget cannot be fetched
```suggestion
    // Use the hardcoded back-up gas price if gas price cannot be fetched
```

2022-05-27 11:28 UTC, amarthadan commented on src/gas-oracle.ts
> +  return recommendedGasPriceMultiplier ? multiplyGasPrice(gasPrice.data, recommendedGasPriceMultiplier) : gasPrice.data;
I would reverse this condition just so that the code flow follows the fallback flow better. If we have the gas price from the provider, we use that. And if we don't, we use the hardcoded one.

2022-05-27 11:28 UTC, amarthadan commented on README.md
> +- `recommendedGasPriceMultiplier`: (optional) - The multiplier to apply to the fallback gas price reported by the
I would add a note that the `recommendedGasPriceMultiplier` will not be used on the `fallbackGasPrice` and so that `fallbackGasPrice` will be used as is in the config file.

2022-05-27 14:39 UTC, vponline commented on config/airseeker.example.json
> +        "txType": "legacy",
It was decided to stick with `strings` in the configs for readability, but to use the legacy type, so I changed this in the `airseeker.example.json` to match.

2022-05-27 14:45 UTC, vponline commented on src/gas-prices.ts
> +  chainOptions: node.ChainOptions & { gasPriceMultiplier?: number },
Sorry about not clarifying this in the description. Since the gas oracle is supposed to always return a (legacy) `gasPrice`, I switched to using the provider.getGasPrice method directly instead of using the `gas-prices.ts` (these are no longer used at all, but I did not remove the files in this PR). 

We could still use Airnode's `getGasPrice` because it supports different txTypes if needed, so please let me know and I can make the changes.

2022-05-27 14:48 UTC, vponline commented on src/gas-prices.test.ts
> +                  gasPriceMultiplier,
I didn't add it since it's an optional field and only used in the gas-prices.ts getGasPrice implementation (and those methods are not used in the gas-oracle).

The gas-oracle has a separate multiplier: `recommendedGasPriceMultiplier`.  This setup is a bit confusing, but allows different multipliers if we want to somehow combine both gas-price and gas-oracle?

2022-05-27 14:50 UTC, vponline commented on src/gas-prices.ts
> +  gasPrice.mul(BigNumber.from(Math.round(gasPriceMultiplier * 100))).div(BigNumber.from(100));
I was anticipating that we would delete **gas-prices.ts** entirely but was not sure if that should be done here (I guess so if the gas-oracle implementation is approved)

2022-05-27 14:55 UTC, vponline commented on README.md
> +- `maxTimeout`: (optional) - The maximum timeout (in seconds) for fetching a block or fallback gas price (defaults to
> Do we need this configurable? 
Maybe :smile:. It depends on if we are fine with a 5 second timeout or if that may be too long (within a cycle). I made it configurable just in case.

2022-05-28 08:26 UTC, bbenligiray commented on config/airseeker.example.json
> +        "txType": "legacy",
Weren't we supposed to use `"0"` or `"2"`? Or was that only for Airnode?

2022-05-30 06:16 UTC, vponline commented on src/gas-oracle.ts
> +  if (blockPercentileGasPrices.length > 1) {
You're right, I wrote it like this in case we needed to add more blocks (there was talk of using 3 + 1 reference block before), but it's an easy change if needed so I will change this check to `=== 2`.

2022-05-30 11:53 UTC, vponline commented on src/gas-oracle.ts
> +        block.data.transactions.map((tx) => (tx.gasPrice || block.data.baseFeePerGas!.add(tx.maxPriorityFeePerGas!))!)
In practice, it seems that `gasPrice` is always returned on all EIP1559 chains as well, even though ethers says that it would be `null`.

Conversely, ethers says that the EIP1559 values would be null on non-EIP1559 chains.

2022-05-30 11:57 UTC, vponline commented on test/e2e/airseeker.feature.ts
> -  it('updates the beacons successfully with one invalid provider present', async () => {
This should not have been removed, I've added it back.

2022-05-31 07:15 UTC, amarthadan commented on config/airseeker.example.json
> +        "txType": "legacy",
Let's deal with this when adding the strategies feature (for reference https://api3workspace.slack.com/archives/C037NLX1R8T/p1653813343064269), keeping it as it is for now.

2022-05-31 07:17 UTC, amarthadan commented on src/gas-prices.ts
> +  chainOptions: node.ChainOptions & { gasPriceMultiplier?: number },
Ok, let's keep the `gas-price.ts` there, unused, for now and we will revisit it when working on the support of multiple strategies.

2022-05-31 07:27 UTC, amarthadan commented on src/gas-oracle.ts
> +        block.data.transactions.map((tx) => (tx.gasPrice || block.data.baseFeePerGas!.add(tx.maxPriorityFeePerGas!))!)
I would add some conditions just to be on the safe side. We use a fallback if we don't have the necessary data for the calculation anyway. I just want to avoid potential unnecessary exceptions.

2022-05-31 17:46 UTC, vponline commented on src/gas-oracle.ts
> +        block.data.transactions.map((tx) => (tx.gasPrice || block.data.baseFeePerGas!.add(tx.maxPriorityFeePerGas!))!)
I've added a check for this (and a few unit tests), please see [here](https://github.com/api3dao/airseeker/pull/75/files#diff-38619592ec5069b9dc3cf986de32e5294ae2b0d5acd47aaf650cbf9463108016R96-R105) and let me know what you think.

2022-05-31 18:21 UTC, vponline commented
I believe that covers all revisions since we're leaving the config changes for later, so please re-review :smile:

2022-05-31 18:23 UTC, vponline commented on src/gas-prices.ts
> +  chainOptions: node.ChainOptions & { gasPriceMultiplier?: number },
Ok sounds good, hopefully by then the imported Airnode config type will include `gasPriceMultiplier` as well

2022-06-02 08:07 UTC, amarthadan approved these changes
Ok, some cosmetic nits but other than that I think it's good to go :+1:

2022-06-02 08:07 UTC, amarthadan commented on src/gas-oracle.ts
> +  // Check percentileGasPrices only if we have the result from at least two blocks
A bit misleading comment.

2022-06-02 08:07 UTC, amarthadan commented on src/gas-oracle.test.ts
> +          ],
Won't this fall under the `not enough transactions` check instead of the `can't compute gas price from the eip1559 transaction` check?

2022-06-02 08:07 UTC, amarthadan commented on src/gas-oracle.ts
> +      : gasPrice.data;
Maybe we can use the multiplier before logging so we log the price we're actually using.

2022-06-02 08:07 UTC, amarthadan commented on src/gas-oracle.test.ts
> +    it('returns config backupGasPriceGwei gas if failing to fetch both blocks and fallback', async () => {
I think there's no `backupGasPriceGwei` field, right? Is this the old name? Can you update it?

2022-06-02 08:07 UTC, amarthadan commented on test/e2e/gas-oracle.feature.ts
> +      it('uses fallback backupGasPriceGwei when getBlockWithTransactions and getGasPrice provider calls fail', async () => {
I think there's no `backupGasPriceGwei` field, right? Is this the old name? Can you update it?

2022-06-02 08:32 UTC, vponline commented on test/e2e/gas-oracle.feature.ts
> +      it('uses fallback backupGasPriceGwei when getBlockWithTransactions and getGasPrice provider calls fail', async () => {
Yep, nice catch, will fix!

2022-06-02 08:44 UTC, vponline commented on src/gas-oracle.test.ts
> +          ],
You're right, will fix

2022-06-02 10:37 UTC, bbenligiray commented on config/airseeker.example.json
>          "baseFeeMultiplier": 2,
These probably shouldn't be in the same object as `gasOracle`

2022-06-02 11:06 UTC, vponline commented on config/airseeker.example.json
>          "baseFeeMultiplier": 2,
Do you mean that the `gasOracle` object should not be in `<chainId>.options`? `priorityFee` and `baseFeeMultiplier` will not be used currently so should we leave moving these fields for the config refactor task?

2022-06-02 11:19 UTC, bbenligiray commented on config/airseeker.example.json
>          "baseFeeMultiplier": 2,
Okay, I just meant that unused fields should be removed

2022-06-02 11:48 UTC, vponline commented on config/airseeker.example.json
>          "baseFeeMultiplier": 2,
Got it,I'll remove them since we are using `txType` 'legacy' anyway.

2022-06-02 12:59 UTC, acenolaza approved these changes
Reviewed things that I had pointed out and all of them got resolved or answered. LGTM 👍🏻

2022-06-02 12:59 UTC, acenolaza commented on src/update-beacons.test.ts
> -    expect(api.calculateTimeout(startTime, totalTimeout)).toEqual(2000);
Just double checking. The decision is to keep these 2 tests here, correct?

2022-06-02 13:04 UTC, vponline commented on src/update-beacons.test.ts
> -    expect(api.calculateTimeout(startTime, totalTimeout)).toEqual(2000);
I think it's a good idea to move them as well, but perhaps we can leave that for a later task (e.g. with the config changes)?

2022-06-02 19:12 UTC, merged