BEC-307: Add more thorough validation for configuration file
api3dao/airseeker-v1 pull request #76
Opened 2022-05-05 21:28 UTC by acenolaza

Pretty self explanatory 😁 but basically moved validations related to the config that were spread around the code to the validations.ts file and used zod refinements to validate those checks on startup.

2022-05-06 09:54 UTC, vponline commented on test/e2e/airseeker.feature.ts
> -    mockReadFileSync(
This is removed because the validator won't let an invalid beacon in the config to pass, but I'm wondering if we should still have tests where we make sure that the Airseeker will run correctly for valid beacons even if an invalid one somehow made it to deployment?

This would require mocking the loadConfig function instead of mocking the `fs` function (so that the validator is esentially bypassed for this test, we did it like this in [Airkeeper](https://github.com/api3dao/airkeeper/blob/main/test/e2e/psp.feature.ts#L270)).

Just a thought, WDYT?

2022-05-06 14:06 UTC, acenolaza commented on test/e2e/airseeker.feature.ts
> -    mockReadFileSync(
I had that same exact concern when removing these tests (which is always scary thing to do 😁) but since the validations no longer exist in the code that process the triggers then the code will probably fail or even crash if the config has invalid values. That is also why I added quite a few tests to the validation.test.ts file in order to make sure that the app will not start if it has any invalid values in the config.

An alternative could be to have replace these tests with other tests that expect the app to fail or crash if there are invalid values in the config but that is not something we really expect I guess.

2022-05-06 14:59 UTC, vponline commented on test/e2e/airseeker.feature.ts
> -    mockReadFileSync(
Thanks for explaining. I guess there is no way for a `beaconId` to suddenly go `invalid` while the Airseeker is running so perhaps these are not necessary :+1:

2022-05-10 11:22 UTC, amarthadan requested changes
I very much like this PR. I think both code and tests are way cleaner without the validation and all the validation is in one place :+1:

2022-05-10 11:22 UTC, amarthadan commented on src/providers.test.ts
> -        '2': {},
Why is ok to remove this without changing anything else?

2022-05-10 11:22 UTC, amarthadan commented on src/providers.ts
> +  const sponsorBeaconsByChainId = Object.keys(config.triggers.beaconUpdates);
The name `sponsorBeaconsByChainId` suggests that the variable has a structure like:
```
{
  <chain ID>: <beacon object>,
  ...
}
```
which is not true. I think calling it `chains` is fine.

2022-05-10 11:22 UTC, amarthadan commented on src/validation.ts
> +    const template = config.templates[beacon.templateId];
If you go just through the referenced templates you can have a template in `templates` that is not referenced in `beacons` and it would pass. I don't think we want that, do we?

2022-05-10 11:22 UTC, amarthadan commented on src/validation.ts
> +  .superRefine(validateTriggersBeaconUpdates);
I think the names are a bit confusing. For example, you're calling the function `validateBeacons` but you're also validating template IDs. I would probably go with a separate function for each validation, something like `validateBeaconIDs`, `validateTemplateIDs`, `validateBeaconTemplateReferences`, etc. WDYT?

Also, can you add a validation that the referenced gateway exists (the `airnode` in `beacons` and a key in `gateways`)?

2022-05-10 11:22 UTC, amarthadan commented on src/validation.test.ts
> +it('fails if derived beaconId is different to beacons.beaconId', () => {
Is this title correct? You're changing the template ID, not beacon ID.

2022-05-10 11:22 UTC, amarthadan commented on src/validation.test.ts
> +      },
Why is there a message that beacon ID is invalid?

2022-05-10 13:22 UTC, acenolaza commented on src/providers.test.ts
> -        '2': {},
Because previous to these changes the validation in the code would handle that trigger and just ignore it. Now that's no longer being handled in the code and the test is not validating the config therefore test will fail. That value should never be there if the config validation is run during startup tho.

2022-05-10 13:28 UTC, acenolaza commented on src/providers.ts
> +  const sponsorBeaconsByChainId = Object.keys(config.triggers.beaconUpdates);
Yes, the new name is not super accurate but I thought that chains could be misleading to the one reading the code since there is a top level [chains object](https://github.com/api3dao/airseeker/blob/bec307-custom-config-validation/config/airseeker.example.json#L15) in the config file.

I don't feel this change is too meaningful so I can revert it to `chains` or use a different one. Maybe `beaconUpdatesChains`? Naming things is really hard 😅

2022-05-10 13:52 UTC, acenolaza commented on src/validation.ts
> +    const template = config.templates[beacon.templateId];
Well that wasn't being validated even before these changes because the app perform actions based on the items under `beacons` (triggers). 

For instance in Airkeeper I usually had many test templates and endpoints that were not being referenced in the triggers at one point but while testing I would switch between them (referencing ones and stop referencing others).

Bottom line is that since we are iterating over the triggers then all things referenced by them must exist but I'm not sure if we should also check for things not being in used by the triggers.

2022-05-10 15:46 UTC, acenolaza commented on src/validation.ts
> +  .superRefine(validateTriggersBeaconUpdates);
I called them like that mainly based on the thing I'm iterating over:
```
validateBeacons -> config.beacons
validateTriggerBeaconUpdates -> config.triggers.beaconUpdates
```
I don't mind using the names you are suggesting but that would require looping over the same `config.beacons` list more than once. Would that be OK you think?

2022-05-10 15:49 UTC, acenolaza commented on src/validation.test.ts
> +it('fails if derived beaconId is different to beacons.beaconId', () => {
I think you make a good point here. I was changing one of the components used when computing the `beaconId` hash but the test might be more accurate if I change the `beaconId` instead.

2022-05-10 15:51 UTC, acenolaza commented on src/validation.test.ts
> +      },
Basically because of [this](https://github.com/api3dao/airseeker/pull/76#discussion_r869414267). 
`BeaconID = hash(airnode, templateId)`

2022-05-10 17:50 UTC, acenolaza commented on src/validation.test.ts
> +      },
Disregard my previous comment. It turns out one of those tests were redundant so ended up removing it.

2022-05-11 06:31 UTC, amarthadan commented on src/providers.ts
> +  const sponsorBeaconsByChainId = Object.keys(config.triggers.beaconUpdates);
Yeah, `beaconUpdatesChains` sounds good.

2022-05-11 06:33 UTC, amarthadan commented on src/validation.ts
> +    const template = config.templates[beacon.templateId];
Ok. I thought that we would allow only what's referenced and if something is not referenced it would be considered an issue. But I understand your reasoning, it makes sense to allow unused bits that are not referenced.

2022-05-11 06:41 UTC, amarthadan commented on src/validation.ts
> +  .superRefine(validateTriggersBeaconUpdates);
I understand and think that would be fine. I mainly suggested the names just so you can tell just by glancing at it what's getting validated. But if you think that it would be a lot slower and it doesn't really bring much value feel free to keep it as it is :slightly_smiling_face:

2022-05-11 06:47 UTC, amarthadan requested changes
Can you add a validation that the referenced gateway exists (the `airnode` in `beacons` and a key in `gateways`)?

2022-05-11 19:56 UTC, acenolaza commented on src/validation.ts
> +  .superRefine(validateTriggersBeaconUpdates);
I think you'll be pleased with [this](https://github.com/api3dao/airseeker/commit/a2b76debb4aa35620b1edad55728b0864cac18b6) last commit 🤞🏻 😅  

Now I just need to add the gateway reference check 💪🏻

2022-05-11 20:10 UTC, acenolaza commented on src/validation.ts
> +  .superRefine(validateTriggersBeaconUpdates);
Done!

2022-05-11 20:11 UTC, acenolaza commented
> Can you add a validation that the referenced gateway exists (the `airnode` in `beacons` and a key in `gateways`)?

Done! https://github.com/api3dao/airseeker/pull/76/commits/b4bbf3e82ece36745dc1e41ae1e09e6d609dcdc4

2022-05-12 07:28 UTC, amarthadan approved these changes
Awesome :+1:

2022-05-12 07:28 UTC, amarthadan commented on src/validation.ts
> +});
You were right, I very much like this :smile:

2022-05-12 11:52 UTC, merged