Add Serverless Lambda
api3dao/airseeker-v1 pull request #91
Opened 2022-05-12 10:46 UTC by aquarat

Not sure if this should be merged :shrug:

2022-05-18 08:05 UTC, amarthadan requested changes

2022-05-18 08:05 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +The app won't immediately start (due to the scheduler). You can jumpstart the app by calling
That will potentially cause two Airseeker runs to overlap for up to 13 minutes, right? Is that ok?

2022-05-18 08:05 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
This will invoke the lambda on AWS, not locally, right? Why run it in the background?

2022-05-18 08:05 UTC, amarthadan commented on src/main-handler.ts
> +main();
Maybe I'm missing something. The content of this file is the same as was the content of `index.ts`. Why can't we just use the `index.ts`?

2022-05-18 08:05 UTC, amarthadan commented on src/main.ts
>  }
I would propose moving this function to a separate file, something like `serverless.ts` as it's an environment-specific "hack" and not a main functionality.

2022-05-18 08:05 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
Can you explain this a bit more? AFAIK even though the `main` function finishes, node waits for any unfinished async functions. That's probably not the case with lambdas, right? How does this promise help with that? It resolves immediately, doesn't it?

2022-05-18 08:15 UTC, Siegrift commented on src/main.ts
> +  await new Promise((_resolve) => {});
>  It resolves immediately, doesn't it?

This one never resolves. (And I'll let @aquarat answer the other questions).

2022-05-18 08:23 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
So, does it (a)waits forever and we're just waiting for AWS to kill it?

2022-05-18 08:25 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +The app won't immediately start (due to the scheduler). You can jumpstart the app by calling
I'm not sure when the scheduler is triggered initially? I'm struggling to find documentation for it.
If they overlap, the worst thing is that we'll have more provider and RPC calls and we'll pay a little more for the runtime :shrug:

2022-05-18 08:27 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
I should probably add something extra here:
This invokes the cloud hosted Lambda, which won't return for 15 minutes, so the `&` lets you use the terminal until the command dies or times out.
A better approach might be to store the PID of the sls process, wait 10 seconds and then kill that PID.

2022-05-18 08:28 UTC, aquarat commented on src/main-handler.ts
> +main();
Lambda doesn't execute a file, it calls a function, so the working function must be exported in a file that does not have the `main()` call.

2022-05-18 08:28 UTC, aquarat commented on src/main.ts
>  }
Fine with me :)

2022-05-18 08:29 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +The app won't immediately start (due to the scheduler). You can jumpstart the app by calling
I think you normally provide a schedule with a cron job syntax and this is just an abbreviation by serverless. So, I would guess something like `*/13 * * * *`.

2022-05-18 08:35 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
> That's probably not the case with lambdas, right? How does this promise help with that? It resolves immediately, doesn't it?

AFAIK Node won't quit if you have waiting callbacks, which is why this application works correctly in a "conventional" environment. On Lambda, however, the runtime will "freeze" if you don't explicitly handle promise resolution in the handler function. What's weirder is that dangling `async` calls will resume executing when the Lambda is invoked again (thawing).

The timeout blocks indefinitely until AWS kills it. You have graceful signal handling in Airseeker, which is pleasing to see, it's elegant and _correct_ but it isn't necessary imo/AFAIK because you don't have a dirty state that needs to be cleaned up; if the Node process quits all associated resources will be garbage collected. It's not like a database that has to flush its writes to disk before quitting for consistency. Therefore having AWS kill the runtime on timeout is an efficient approach - and I suspect it'd be adequate in conventional Node too, aka `process.exit(0)`;

2022-05-18 08:37 UTC, aquarat commented
As always, thanks for the comments, I'll make the changes soon :)

2022-05-18 10:27 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
Oh, I thought that it will just start the lambda but the prompt is returned to you. But it still runs on AWS and it logs to CloudWatch, right? What you see is just a copy of STDOUT? Would it even stop the process if you would send SIGINT (Ctrl-C)?

2022-05-18 10:34 UTC, amarthadan commented on src/main-handler.ts
> +main();
I understand that but where are you importing `index`? Lambda will execute `src/main.serverlessHandler`, which has nothing to do with it. The only place you use `main-hanlder.ts` is the pm2 configuration and you're just replacing the `index.js` there.

2022-05-18 10:45 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
The signal handling is fine, the "graceful" part is unnecessary and actually quite annoying and should be removed. Sorry, that's on me :see_no_evil:

Two concerns:
* Does the lambda clean its context if the lambda itself kills the processing? Won't we have two (or more) Ariseekers running in the next lambda?
*   > and I suspect it'd be adequate in conventional Node too, aka process.exit(0)
  
    I actually doubt that, I'd say it will be something like `kill -9 <PID>` (not that it matters that much). But my concern is that every lambda will technically fail, right? From the AWS's point of view. It will be also logged that way if I'm not mistaken.

2022-05-18 12:08 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +The app won't immediately start (due to the scheduler). You can jumpstart the app by calling
That's what I thought @ cron expression... but it seems that it might be based on the creation time of the scheduler.

2022-05-18 12:14 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
It is not a copy of stdout. Lambda expects handlers to return an HTTP response object AFAIK, like this:
```
export const chainValueDataPoint: APIGatewayProxyHandler = async (event): Promise<any> => {
  return {
    statusCode: 200,
    headers: {something: 'something'},
    body: JSON.stringify({time: Date.now()}),
  };
```
The function never returns so you would not see anything until it times out and then it would be an error message.

I don't know for sure if terminating the command early would also terminate the Lambda.

2022-05-18 12:19 UTC, aquarat commented on src/main-handler.ts
> +main();
I ran into this problem when I tried deploying to GCP. GCP Cloud Functions rely on the `package.json` defined `main` field.
This will be a problem if we try importing resources from Airseeker in other projects via the index. Anything that relies on the `main` field in `package.json` will call `main()` on import.

2022-05-18 12:28 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
> Sorry, that's on me see_no_evil
I thought it was cool :)

> Ariseekers running in the next lambda?
That's an interesting point, I will check the logs but it seems to kill off everything on each cycle - for instance the RAM usage per cycle is fairly consistent at between 160 and 180 MB.

> From the AWS's point of view. It will be also logged that way if I'm not mistaken.
You're right, looking at the Lambda metrics graphs AWS regards every run as an error.
> Task timed out after 900.11 seconds

2022-05-18 13:02 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
It actually looks like it retries executing the Lambda on an error, so we effectively have two Lambdas running concurrently (!) but in different execution contexts. Thanks for querying this.

2022-05-18 13:06 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
> The function never returns so you would not see anything until it times out and then it would be an error message.

I understand why but that's quite an odd behavior. It would be nice if you could document that.

> I don't know for sure if terminating the command early would also terminate the Lambda.

I don't think it does but it's worth checking. Imagine a situation where someone runs this, it starts a process in the background and the person turns their PC off. The system will try to gracefully kill the process (which is, if I'm not mistaken, pretty much sending SIGINT/SIGTERM) and lambda would stop. I know it's a bit of a stretch but the process is running for about 15 minutes and that's enough time to forget about some process in the background. This behavior should be IMO properly documented.

I would also mention that this WILL NOT start the Airseeker "cycling", once this call is done the Airseeker (that one lambda) stops and that's it. So, I'm not sure if "jumpstart" is the right word.

2022-05-18 13:14 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
> so perhaps AWS completely resets the environment on error.

:man_facepalming: It does. I haven't realized it's actually an error even though I wrote it a bulletpoint later :joy: Yes, every time I re-tried lambda from an error state it was basically a cold-start so I presume it does.

> You're right, looking at the Lambda metrics graphs AWS regards every run as an error. The status message in the logs is "Task timed out after 900.11 seconds"

That's quite unfortunate (and by unfortunate I mean ugly :joy:) We're technically giving up any chance of using AWS alerting or anything like that. And we will be doing the same for GCP and any other cloud provider for that matter. If we would want to check any problems in functions run (on the cloud provider layer I mean) we won't be able to filter them efficiently as they will be all failed.

2022-05-18 13:16 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
> It actually looks like it retries executing the Lambda on an error, so we effectively have two Lambdas running concurrently (!) but in different execution contexts. Thanks for querying this.

I think that retry behavior is configurable.

2022-05-18 13:24 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
> I think that retry behavior is configurable.

Yes it is, I have just added a commit to fix this :) Thanks again for leading me down this path.

> That's quite unfortunate (and by unfortunate I mean ugly) 

The benefit of the error scenario is we start fresh every 15 minutes it seems, which removes any leftover state, but I get what you're saying, not ideal. I wonder if we could call `process.exit(0)` in a Lambda? Or enumerate all callbacks globally and destroy them.

2022-05-18 13:27 UTC, amarthadan commented on src/main-handler.ts
> +main();
I see. But don't you need the same blocking behavior as in `serverless.ts` for GCP as well? Because in this setup GCP will access `main.js` (as stated in `package.json`) exporting the `main` function and you can run just that. You won't be able to access `handler` function from `serverless.ts`.

2022-05-19 06:16 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
I think that any effort to improve this would be just a waste of time and would result in a more complex code. Also, we kinda rely on the state being cleaned and that happens only for failed lambdas. So, I don't think we can do much here. Lambdas are just not designed to be used this way.

2022-05-19 08:02 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
I've just tested and if you kill the local invoke the target Lambda doesn't stop.

I'll update the documentation to reflect the above nuances.

2022-05-19 08:46 UTC, aquarat commented on src/main-handler.ts
> +main();
`index.ts` should ideally export everything exportable, I'll modify it to do that assuming you agree.

2022-05-19 08:59 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
I think that's unfair.

My goal was to quickly adapt Airseeker to Lambda and that has been successful. Airseeker with minimal additional code runs largely perfectly on Lambda. It's cheap, it's reliable and it's very simple to deploy and tear down. The only deficiency as it currently stands is the termination of the handler and that's a product of the application spawning untracked promises and relying on a global state for signalling termination. This isn't an inherently incorrect approach, it's what you went with as ECS as a target.

The bulk of this work took half a day, which is a great return on time invested. It's this discussion that's taken much longer.

No one is suggesting that your work be thrown out or heavily modified. We're looking at co-existence, which is what this PR delivers.

2022-05-19 09:14 UTC, amarthadan commented on src/main.ts
> +  await new Promise((_resolve) => {});
I'm not dissing the solution or its time/value efficiency. I'm just saying that Lambdas are not designed to live for a long time and when they timeout they technically fail with an error. Those are facts. And if you want to take advantage of the state being cleaned you need to let the lambda fail, otherwise the state will be frozen and used for another run, right? I'm just making sure we're aware of the tradeoffs, that's all. Sorry, if I sounded harsh, it wasn't meant to be that way.

2022-05-19 09:18 UTC, amarthadan commented on src/main-handler.ts
> +main();
> `index.ts` should ideally export everything exportable, I'll modify it to do that assuming you agree.

I'm fine with that but the question still stands. Don't you need the blocking behavior for GCP as well?

2022-05-19 10:08 UTC, aquarat commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
I have added the detail to better describe what's going on, LMKWYT

2022-05-19 10:19 UTC, amarthadan commented on aws-lambda-deploy-guide.md
> +yarn sls invoke --function airseeker &
Sounds good :slightly_smiling_face:

2022-05-19 10:22 UTC, aquarat commented on src/main-handler.ts
> +main();
I doesn't look like GCP requires the blocking behaviour (although I included it): https://github.com/api3dao/airseeker/blob/add-gcp/src/main.ts

But GCP does require an HTTP server for health checks.

I'm getting a little lost with what you'd like. From what I can see we need 
- an index file (package.json->main referenced) which exports everything in Airseeker without running anything.
- A direct execution entry point (was in `index.ts`, now is in `main-handler.ts`, probably a bad name, maybe it should be called `entry-point.ts`
- The _main_ application logic (currently exported as `main` in `main.ts`, perhaps should be named `airseeker.ts`)
- Serverless handler stub file (`serverless.ts`), will contain a handler for GCP and a handler for Lambda (they have slightly different requirements)

2022-05-19 10:24 UTC, amarthadan commented on serverless.aws.yml
> +    maximumEventAge: 60
This doesn't do anything if we have no retries, does it?

2022-05-19 10:27 UTC, aquarat commented on src/main.ts
> +  await new Promise((_resolve) => {});
No problem :pray: I appreciate it :)

You are correct^
Lambdas are not designed to live for a long time, where a long time is longer than the timeout. This varies greatly between providers, for instance GCP can do an hour timeout on [Gen 2 Cloud Functions](https://cloud.google.com/functions/docs/2nd-gen/overview#:~:text=For%20event%2Dtriggered%20functions%2C%20the,intensive%20and%20more%20parallel%20workloads) and Azure has no timeout. GCP and Azure are very close to ECS in behaviour from what I can tell.

I think the 15 minute interval and associated state clean isn't a bad thing. I know you didn't architect the app to work like this, but it does work and it works well - but again, it's one of multiple solutions that should co-exist :)

2022-05-19 10:28 UTC, amarthadan commented on src/main-handler.ts
> +main();
I was just trying to understand what will be used where and how. Let's rename `main-handler.ts` to `entrypoint.ts` and I think it's fine.

2022-05-19 10:32 UTC, aquarat commented on serverless.aws.yml
> +    maximumEventAge: 60
You're right, I'll remove it. Paranoia.

2022-05-19 10:44 UTC, aquarat commented on src/main-handler.ts
> +main();
Awesome, thank you :)

2022-05-19 11:06 UTC, amarthadan approved these changes

2022-05-19 12:14 UTC, merged